### ISSUE TITLE
Multi user System: Ubuntu 17.04 - icon shows red, daemon not restartable

### ISSUE THREAD

**Issue by rumplstielz** [lah7/polychromatic#100]
Hi,
I have a multi user system. The problem: when I am logged in as one user and switching to another user, the icon goes red, which seems to show that the daemon is not running. 
Restarting the daemon from the context menu of the polychromatic icon also does not work (stays at "killing daemon"). 

I am not sure if this is the correct forum, as the daemon is not your bussiness, but maybe you can help?!

br,
rumpl

**Comment by lah7** [comment]
Most likely the other user is not part of the `plugdev` group, so the daemon is unable to start (or in this case, hangs). Starting the Controller will alert you if that's the case.

You can set this from the terminal:

    sudo gpasswd -a <username> plugdev

**Comment by rumplstielz** [comment]
both users are in the plugdev group. 46(plugdev) --> I only see the problem if both users are logged in. The first user sees the icon + daemon ok. When you login with the second user you see the problem with this second user.

**Comment by lah7** [comment]
Sorry, I don't really know what to suggest as it's a daemon issue. There might be a technical reason why it works for the first user but not other logged in users... like if the daemon needs exclusive control. :thinking: 

Please raise the problem with the [driver/daemon people](https://github.com/terrycain/razer-drivers) and provide them with the daemon's log from `~/.razer-service/logs/razer.log`, or run it from the terminal on the second user (providing the daemon isn't running on that user):

    razer-daemon -F 

Considering Polychromatic gets stuck at the "Killing daemon" part, it may have truly hung. If it produces a stacktrace, even better.
