### ISSUE TITLE
Issue with git versioning code in stable build

### ISSUE THREAD

**Issue by JFK422** [lah7/polychromatic#101]
After installing this app over the stable ppa, the app shows up shortly in the taskbar an closes afterwards. I did some reseach and found a command in a Desktop file leading to [this](https://drive.google.com/open?id=0B_4FrWDVmFvGUlYxbVVwdjJrR00) error. I tried to fix it by editing the code, but no luck.

**Comment by lah7** [comment]
Ugh, merge problems. Sorry about that, I'll get this fixed up ASAP.

**Comment by lah7** [comment]
Actually, it was just a hiccup with Ubuntu/Debian packaging -- new packages will be in the PPA soon, or [grab an updated deb](https://github.com/lah7/polychromatic/releases/download/v0.3.9.3/polychromatic_0.3.9.3-1_all.deb).  Thanks for spotting this! :+1:
