### ISSUE TITLE
Add "starlight" matrix effect

### ISSUE THREAD

**Issue by zeus86** [lah7/polychromatic#105]
The Driver - at least in Version 1.1.14 - already supports the so called "starlight" effect, which is afaik also available in the Windows-Version of the Razer Userland-Tools. It would be nice, if the corresponding GUIs like polychromatic would also support this. I don't know which devices are capable of using this, but on my Chroma V2 this works like a charm.

```
zeus@linux:/$ > ls -al | grep starlight
--w--w---- 1 root plugdev 4096 Jul 14 19:16 matrix_effect_starlight
zeus@linux:/sys/bus/hid/drivers/razerkbd/0003:1532:0221.0004$ 
> dpkg -l | grep -i razer
ii  polychromatic              0.3.9.3-1-xenial  all   Graphical front-end for managing Razer peripherals.
ii  python3-razer              1.1.14-0ubuntu1   all   Razer Python Library
ii  razer-daemon               1.1.14-0ubuntu1   amd64 Razer Device Daemon
ii  razer-doc                  1.1.14-0ubuntu1   all   Documentation and examples for the Razer Tools
ii  razer-kernel-modules-dkms  1.1.14-0ubuntu1   amd64 Razer Peripheral Drivers
```
For example, this gives a nice white/yellow-ish starlight:
```
zeus@linux:/sys/bus/hid/drivers/razerkbd/0003:1532:0221.0004$ 
> echo -n -e "\x02\xFF\xFF\xFF\xFF\xBB\x00" > matrix_effect_starlight

```

**Comment by lah7** [comment]
Polychromatic uses the daemon to alter lighting effects, but starlight is available as an option if the daemon says so.

Please run this command and paste me the capabilities for your BlackWidow Chroma V2 so we can check:

```
polychromatic-controller --print-device-info
```

**Comment by zeus86** [comment]
the output does not mention the starlight effect at all. this seems awkward, because as already mentioned the driver is capable to run this effect properly. maybe it just does not reports when asked via the api?

```
# Device Info
Name: Razer BlackWidow Chroma V2
Type: keyboard
 
# Device Capabilities
{'lighting_logo_spectrum': False, 'lighting_none': True, 'lighting_scroll_pulsate': False, 'lighting_scroll_blinking': False, 'lighting_pulsate': False, 'lighting_wave': True, 'lighting_led_single': False, 'lighting_logo_reactive': False, 'lighting_scroll_spectrum': False, 'lighting_spectrum': True, 'lighting_breath_single': True, 'lighting_backlight': False, 'lighting_static': True, 'lighting_logo_blinking': False, 'lighting_breath_random': True, 'lighting_backlight_active': False, 'serial': True, 'lighting_logo_breath_dual': False, 'lighting_logo_pulsate': False, 'lighting_breath_dual': True, 'lighting_scroll_none': False, 'lighting_breath_triple': False, 'macro_logic': True, 'lighting_scroll': False, 'lighting_logo_active': False, 'lighting_ripple_random': True, 'lighting_scroll_active': False, 'lighting_ripple': True, 'lighting_scroll_reactive': False, 'lighting_logo_brightness': False, 'macro_mode_led_effect': True, 'lighting_logo_breath_random': False, 'name': True, 'macro_tartarus_mode_modifier': False, 'brightness': True, 'lighting_scroll_breath_random': False, 'lighting_logo': False, 'lighting_logo_static': False, 'lighting_scroll_breath_dual': False, 'lighting_scroll_brightness': False, 'lighting': True, 'type': True, 'firmware_version': True, 'lighting_scroll_static': False, 'lighting_led_matrix': True, 'game_mode_led': True, 'lighting_logo_none': False, 'lighting_logo_breath_single': False, 'macro_mode_led': True, 'lighting_scroll_breath_single': False, 'lighting_reactive': True}
```
by the way, when executing 
`polychromatic-controller --print-device-info`
the tool will crash, when no numerical option is given and return is pressed :-)  :
```
Enter choice: 
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 2751, in <module>
    stdout = Terminal()
  File "/usr/bin/polychromatic-controller", line 2531, in __init__
    self.print_device_capability_info()
  File "/usr/bin/polychromatic-controller", line 2598, in print_device_capability_info
    no = int(sys.stdin.readline())
ValueError: invalid literal for int() with base 10: '\n'

```

**Comment by lah7** [comment]
Thanks for pointing out that minor bug -- squished!

For the daemon, [I had a look at the methods for your BlackWidow Chroma V2 keyboard](https://github.com/terrycain/razer-drivers/blob/master/daemon/razer_daemon/hardware/keyboards.py#L381), and it's set to use starlight.... Yet, when Polychromatic asks what it's capable of, the daemon simply doesn't mention it. Strange bug, any ideas @terrycain?

**Comment by terrycain** [comment]
That would be because the capabilities dict doesn't contain anything for starlight :wink:, @lah7 remind me tonight and ill add that in.

**Comment by zeus86** [comment]
ah, nice, so i can expect this soon to be available? sounds great... by the way, i've seen that the windows-driver support a "fire"-like animation, will that also be available somewhen? 
beside that i dont think that the linux-variant of drivers for blinking gaming gear neccessarily have to be fully feature-compatible with their windows pendant, but i rather think some cool "own" effects would be nice, like raindrops or something (raindrops as in a bit like starfield with a growing corona around it, which becomes dimmer as more far away it moves from it's center of origin), what about that? ^^

anyways, keep up the great work guys.

**Comment by zeus86** [comment]
...and yes, i know that this question would have been better in the issues of the driver and not a gui for that, but it matched here.

**Comment by lah7** [comment]
Fire-like animations would come under "custom effects". :fire:  I'm hoping to put together some sort of process that would make it easier to playback effects written in Python, aiming for the release of **v0.4.0**.

------------
But starlight is now supported "properly" now for the next update (or daily PPA if you're adventurous). I can only test "Random" on my BW Ultimate 2016. Previously there were "_some sort of support_" for starlight, but it was never used (as the daemon didn't support starlight till now, thanks @terrycain for adding that).

**Comment by zeus86** [comment]
yeah, nice, i'd love to test this, but in the daily-ppa currently doesnt contain updated debs. as far as i can see all pkgs are in version 0.3.9.3-1~527 from yesterday, but maybe these get autoupdated or havent been automatically build yet.  i'm running 16.04 on my workstation, the packages have not been updated for that so far, so i'll test this tomorrow or so. 

btw.: custom effects sounds very nice, can't wait to test that.

**Comment by zeus86** [comment]
uhm, 0.3.9.3-1~529 is now inthe ppa, but still no starlight *sigh*.

anyways, i'll test tomorrow

**Comment by lah7** [comment]
You'll also need to be running the latest daemon too. Use this new daily PPA for the daemon (it will be renamed to OpenRazer at some point)

sudo add-apt-repository ppa:openrazer/daily
sudo apt update
sudo apt upgrade

**Comment by zeus86** [comment]
nah, okay, missed that point, i'll test that later today

**Comment by zeus86** [comment]
i installed the updated drivers. works like a charm, just maybe just one more thing:

in the drop down menu i can choose between single dual and random. 
in the controller gui (which is localized to german in my case) i can only choose between dual and random, but not single. of course you can choose both colours the same, but i guess that is not the intended way, and single is just missing, because it is available on other effects like breath. 

by the way the german localization in the controller for this is also already present and correct in the gui and refers to "Sternenhimmel" (literally starsky, meaning nightsky; but "Sternenhimmel" is already the best translation you can get for this [don't know if you guys even speak german...].) the tray itself is not localized so far, if there is support for localization implemented yet, let me know, i'd offer to translate this to german^^.

beside that, starlight effect is working like a charm, thanks for the fast implementation.

**Comment by lah7** [comment]
No problem, thanks for testing this.

I missed out something, the missing "single" option will appear in the next package.

:de: No I don't speak German, the original translation was done by @BlauerHunger. The framework is in place and *should display* for for both the Controller and Tray Applet. [See here on how to translate](https://github.com/lah7/polychromatic/wiki/How-to-translate-the-application), as it's possible strings have changed and are in need of updating.

**Comment by zeus86** [comment]
yeah, after having a closer look, i have seen that the tray is indeed partially translated. i'll have a look onto this these days.
