### ISSUE TITLE
Razer Orochi 2015

### ISSUE THREAD

**Issue by synetax** [lah7/polychromatic#109]
I need help with the Orochi 2015 edition...

$ ls -l /sys/bus/hid/devices/ | grep '1532:'
lrwxrwxrwx 1 root root 0 Jul 27 10:37 0005:1532:0056.0003 -> ../../../devices/virtual/misc/uhid/0005:1532:0056.0003

The driver does seem to work even though it isn't officially listed yet. The issue is that Polychromatic doesn't seem to detect it and I'm not sure how to bind the driver to the device using modprobe as I have relatively little experience with this kind of thing.

Should I wait it out until it's supported?
Any advice is appreciated.

**Comment by lah7** [comment]
The device needs to work with the daemon in order for it to work in Polychromatic.

I don't believe your model device is supported, as I can't see `1532:0056` or "Orochi 2015" referenced in the [driver/daemon repository](https://github.com/terrycain/razer-drivers/issues?utf8=%E2%9C%93&q=is%3Aissue%201532%3A0056%20) at all. I am assuming it's `1532:0056`, but check with `lsusb | grep 1532`

You should [raise an issue](https://github.com/terrycain/razer-drivers/issues) on that repository instead providing this information:

> - Please post the output of
>         `lsusb -d 1532:0056 -v`
>  and
>         ` ls -lah /dev/input/by-id/`
> - Read [this](https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol) because we probably need packet captures.
> - Screenshots of all available options on Razer Synapse are needed.
> - And lastly, the product & model number of the device for documentation reasons please.

**Comment by synetax** [comment]
Okay, thanks.
