### ISSUE TITLE
Ripple not working on Ornata

### ISSUE THREAD

**Issue by coreyog** [lah7/polychromatic#110]
Setting the lighting effect to Ripple won't change anything. If the device was static, it stays static, if it was reactive, it stays reactive, etc. The UI gives no errors, the keyboard continues to behave like that setting was never changed.

Razer Ornata (the green only version, not Chroma)

**Comment by lah7** [comment]
It's likely to be a bug in the daemon, as it is responsible for producing the ripple (it's a software effect). I'd suggest [raising an issue there instead](https://github.com/terrycain/razer-drivers/issues) as Polychromatic is merely just interfacing with the daemon.

To completely rule out Polychromatic being at fault, try interfacing with the Python library directly -- open a terminal and run these in `python3`:

```
import razer.client
a = razer.client.DeviceManager()
b = a.devices[0]          // Assuming it's the only device
b.name
b.fx.ripple(255,255,255, 0.1)
b.fx.ripple(255,255,255, 0.01)
b.fx.ripple_random()
```

**Comment by coreyog** [comment]
I ran the python and nothing happened. It returned `True` every time so it seems to think it's happening but the hardware doesn't respond.

The daemon project seems to already have [an open issue](https://github.com/terrycain/razer-drivers/issues/166) on this. I commented to say it's also affecting the Ornata.

**Comment by Syncrossus** [comment]
This doesn't happen on my Ornata Chroma, ripple works fine.
