### ISSUE TITLE
Macro Keys function not working with BlackWidow 2012 keyboard

### ISSUE THREAD

**Issue by r2rX** [lah7/polychromatic#114]
Hey all,

I'm currently running Ubuntu 17.04 x64 (w/ Kernel v4.12) using a Razer BlackWidow 2012 keyboard (firmware v1.8). Currently running is the latest Razer driver (via ppa:terrz/razerutils) and Polychromatic (via ppa:lah7/polychromatic).

Everything seems to be working fine, except for the Macro Keys function. Pressing Fn + M (Fn + Right-Alt) doesn't seem to do anything.

Please let me know if there's any additional info required.

**Comment by lah7** [comment]
Hi, please do raise the issue on the [driver/daemon repository](https://github.com/terrycain/razer-drivers/issues) instead, as that's where the macro magic happens and they'll be able to investigate/fix this.

What might be helpful in advance is to run `xev` and paste the output when you press the macro key. *I think* I've seen a similar issue flag up in the past for an older Razer BlackWidow keyboard.

**Comment by r2rX** [comment]
Thanks for the help, @lah7. :)
