### ISSUE TITLE
No lighting drop down menu on Blade Stealth

### ISSUE THREAD

**Issue by ski11ionaire** [lah7/polychromatic#115]
Everything was working fine up until a week or so ago.

Im using Linux Mint 18.1

Although the polychromatic detects my razer stealth keyboard, it gives no options for the lighting effects etc.

See attached image.
![screenshot from 2017-08-10 15-45-48](https://user-images.githubusercontent.com/30823151/29173336-3e848c5c-7de3-11e7-81b9-bb917050accb.png)

I have  removed the PPAs and uninstalled then reinstalled etc. but no luck.

**Comment by lah7** [comment]
There's been a regression in the latest daemon update, which caused the daemon to throw exceptions for Blade Stealth (as a result of adding a logo toggle from #104, which I think has regressed again)

It should work again if you get the latest development build of the daemon, as you're on an Ubuntu-based distro, you can add the PPA:

```
sudo add-apt-repository ppa:openrazer/daily
sudo apt update
sudo apt upgrade python3-razer razer-daemon
```

Once upgraded, remove the daily PPA so you'll get the stable build when that's next released.

**Comment by ski11ionaire** [comment]
This worked 100%
