### ISSUE TITLE
use debugging module to output errors

### ISSUE THREAD

**Issue by ghetolay** [lah7/polychromatic#116]
It looks like that in this commit https://github.com/lah7/polychromatic/commit/e3ac809991faa61f92ae84ece76b75e893344d14 stdout for errors were not refactored. As a result I'm having the following error with the last update : 

>Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 1106, in <module>
    indicator.setup()
  File "/usr/bin/polychromatic-tray-applet", line 180, in setup
    self._setup_failed(_("No devices found."))
  File "/usr/bin/polychromatic-tray-applet", line 443, in _setup_failed
    stdout.error("ERROR: " + error_reason)
 NameError: name 'stdout' is not defined

I think the solution is just about replacing
`stdout.error(...)` into `dbg.stdout(..., dbg.error)` 

I've done that directly on the script and it's working again.

**Comment by lah7** [comment]
Thanks for spotting that -- oops!
