### ISSUE TITLE
Insuffucient permissions (Arch Linux)

### ISSUE THREAD

**Issue by DinckelMan** [lah7/polychromatic#117]
On 4.12.6-1-ARCH, with the application downloaded from polychromatic AUR, the app is complaining about user not being in the plugdev group.

Performing "gpasswd -a <username> plugdev", responds with "Adding user <username> to group plugdev", but to my knowledge the plugdev group does not exist in Arch.

**Comment by lah7** [comment]
Apparently the group gets created during the daemon installation, but as I don't use Arch, I don't know much else.

When the user is added to the group, you must log out and re-log in for the new group to be used.

**Comment by DinckelMan** [comment]
I think you may be right. 

usermod - aG plugdev did the thing after additional manipulations and a few restarts. Still not out of the box behavior.

**Comment by lah7** [comment]
Will summon @z3ntu to have a look, as he takes care of the packaging for Arch.

**Comment by z3ntu** [comment]
The gpasswd command adds the user to the group so the usermod command shouldn't be necessary. Additionally I am looking into getting rid of plugdev and using udev ACLs for permissions.
