### ISSUE TITLE
Dependency on 'dbus-user-session' in Ubuntu breaks seahorse password manager

### ISSUE THREAD

**Issue by EchoCloud** [lah7/polychromatic#122]
Issues associated with this are:
- delayed startup times for chrome/chromium, terminal (when pressing 'control-alt-t')
- unable to use password manager for auto-logins in Ubuntu

Detail is in black/white right here in this thread:
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1689825

**Comment by lah7** [comment]
Polychromatic does not explictly depend on `dbus-user-session` so nothing can be done here. It is actually `openrazer-daemon` that has this dependency.

    apt depends openrazer-daemon
    apt rdepends dbus-user-session

Seems a similar issue has been raised: https://github.com/openrazer/openrazer/issues/358
