### ISSUE TITLE
Unable to adjust brightness or stop the "breathing" effect on my Blackwidow Ultimate 2012

### ISSUE THREAD

**Issue by ChristopherBare** [lah7/polychromatic#124]
Hello, 
After an update or something going on in my system, I am now unable to turn off the "breathing" effect or adjust my brightness. I can, however, activate gaming mode from the polychromatic interface. 

Does anyone have some ideas of how to fix this issue?

**Comment by lah7** [comment]
Hi, sounds like some sort of driver/daemon issue. You may have more luck [raising the issue on their repository](https://github.com/openrazer/openrazer/issues) as really, this app is just telling the daemon to do things.

> After an update or something going on in my system

An update to OpenRazer/Polychromatic or some other packages? Which distro?

Do the logs reveal any errors? 
 * `~/local/share/openrazer/logs/razer.log`? 
 * If you run the command `dmesg`?

**Comment by ChristopherBare** [comment]
When I ran `dmesg | grep razer` it returned:
 ```bash
[   11.016166] razerkbd: loading out-of-tree module taints kernel.
[   11.016199] razerkbd: module verification failed: signature and/or required key missing - tainting kernel
[   11.872302] razerkbd 0003:1532:010D.0001: input,hidraw0: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate] on usb-0000:00:14.0-9.3/input0
[   11.932273] razerkbd 0003:1532:010D.0002: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer BlackWidow Ultimate] on usb-0000:00:14.0-9.3/input1
[   11.932324] razerkbd 0003:1532:010D.0003: input,hidraw2: USB HID v1.11 Mouse [Razer Razer BlackWidow Ultimate] on usb-0000:00:14.0-9.3/input2
[   36.072810] Modules linked in: pci_stub vboxpci(OE) vboxnetadp(OE) vboxnetflt(OE) iptable_filter ip_tables x_tables vboxdrv(OE) joydev binfmt_misc input_leds nls_iso8859_1 nvidia_uvm(POE) mxm_wmi intel_rapl x86_pkg_temp_thermal intel_powerclamp arc4 coretemp kvm_intel snd_hda_codec_hdmi kvm nvidia_drm(POE) uvcvideo nvidia_modeset(POE) irqbypass videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core nvidia(POE) videodev crct10dif_pclmul razerkbd(OE) crc32_pclmul snd_usb_audio media snd_usbmidi_lib ghash_clmulni_intel pcbc snd_hda_codec_realtek snd_hda_codec_generic ath9k snd_hda_intel aesni_intel snd_hda_codec ath9k_common aes_x86_64 ath9k_hw crypto_simd snd_hda_core glue_helper snd_hwdep cryptd snd_pcm ath intel_cstate mac80211 intel_rapl_perf snd_seq_midi snd_seq_midi_event snd_rawmidi 
```

But past that, I'm not too sure what's going on. The log file wan't much help. Just a lot of DEBUG and INFO lines.

**Comment by lah7** [comment]
`module verification failed` might suggest a secure boot problem, which has been known to cause problems with these drivers... but it might not be directly related to this issue.

What options do you see? Have they disappeared after the update or do they now simply "do nothing"?

**Comment by ChristopherBare** [comment]
The options in polychromatic "do nothing" accept for the gaming mode. That one works.

**Comment by lah7** [comment]
Unfortunately, I don't really know what to do as this is a driver/daemon problem. Polychromatic tells the daemon which in term tells your hardware to "do xxx effect" but your hardware isn't complying. 

[Please raise an issue there](https://github.com/openrazer/openrazer/issues) instead, as they may need new pcap captures in case something has changed. Or... it could potentially be a hardware glitch?
