### ISSUE TITLE
Ubuntu 17.10 - Brightness resets after restart

### ISSUE THREAD

**Issue by LarnuUK** [lah7/polychromatic#130]
After restarting, I've noticed that more often than not the brightness of my Razer Anansi is set to 0. Also, the settings on my Naga 2014 all have off for their brightness settings (mouse wheel, logo and side buttons).

This didn't occur on Ubuntu 16.04, the issue has only started after I installed 17.10 (fresh install, not upgrade).

**Comment by lah7** [comment]
Is it just the UI that reports 0 every time, or has the device brightness also been set to zero?

It may likely be an issue at the daemon level, as this is responsible for getting the brightness value of a device. Polychromatic does internally track effects, but relies on the daemon to get the brightness value.

**Comment by LarnuUK** [comment]
The keyboard/mouse are not illuminated no. Changing the brightness on the UI, or via the top bar icon, instantly illuminates the selected device; so would appear that the daemon reporting 0 as the brightness value is the correct value.

**Comment by lah7** [comment]
So, to clarify -- most of the time when you start your computer, both devices are not illuminated, and this didn't happen in 16.04?

I wonder if it's the screensaver on/off functionality in the daemon that may be responsible for this -- open `~/.config/openrazer/razer.conf` and ensure this is set:

    devices_off_on_screensaver = False

Then restart the daemon and set your desired brightness again:

    openrazer-daemon -r

Let me know if this solves it after a reboot. If not, I'd suggest [asking the OpenRazer repository](https://github.com/openrazer/openrazer/issues) as this is driver/daemon related and not an issue with Polychromatic, which is just being told the brightness is zero.

**Comment by LarnuUK** [comment]
Thanks lah7. that did seem to resolve the issue. I gave it a reboot, and also then a hard shutdown, left it a minute or so and then booted back up, and the keyboard and mouse displayed the correct brightness.

Yes, it did work on 16.04, but 17.10 ships with Gnome rather than Unity (which doesn't have a screensaver by default). Perhaps that when the desktop is shutting the brightness is set to 0, as a "screensaver" appear to have activated and not reset to its prior value on boot,

Many thanks for the help.
