### ISSUE TITLE
[BlackWidow Ultimate 2016] ripple lightnight effect not working

### ISSUE THREAD

**Issue by b4tg5s** [lah7/polychromatic#132]
When I select "ripple" as lightnight effect in polychromatic, the illumation either stays dark or reacts according to the last selected effect before choosing ripple. Every other lightning effect does work. I am using the BlackWidow Ultimate 2016, which is supported by the openrazer daemon.

Is this a polychromatic or a driver issue?

**Comment by lah7** [comment]
I'm not 100% certain if my understanding of the problem aligns with the issue at hand, but I'd suspect it'll be a driver or _(most likely)_ a daemon issue, which handles the ripple effect.

Are you saying that ripple sometimes "doesn't work"? If so, does it only happen when switching from specific effects?

* Wave → Ripple
* Static → Ripple
* Reactive → Ripple

**Comment by b4tg5s** [comment]
Actually, it seems like I had overlooked to select a color for the effect. Now, if I activate `ripple` and select a color, the effect just works fine. Issue solve!
