### ISSUE TITLE
Profile Layers

### ISSUE THREAD

**Issue by geordieF** [lah7/polychromatic#15]
Razer synapse has layers in custom lighting, so why cant't theis? I can make it, but I just don't know if it is necessary .

**Comment by lah7** [comment]
It's technically not possible until the driver and daemon supports this and provides an implementation to set effects per keys. It will also require a new save format for profiles.

There's some old discussion here: https://github.com/lah7/razer-chroma-drivers/issues/8#issuecomment-172838310

**Comment by geordieF** [comment]
Lah, we could use canvas and make the colour for each key, then `ctx.getImageData()` the colour.

**Comment by lah7** [comment]
Sorry, I misread the original post. I was thinking of setting effects per keys. :confounded: 

I'd like to keep the editor nice and simple, what's the benefit of having layers for colours?

**Comment by geordieF** [comment]
Setting effects for keys is what I meant. You could do them manually instead of going by the driver, so that it is completely customizable. It's as simple as drawing on a canvas, getting colour data for individual pixels, and set individual key colours based on the pixels on the canvas

**Comment by lah7** [comment]
I'm still not understanding... :confused: We might be thinking about different concepts.

I'm aware Razer Synapse uses layers to set different effects using layers (e.g. Static, Spectrum, Wave, Reactive), is this what you're referring to?

AFAIK, effects per keys are done at hardware level. @terrycain may be able to confirm..

Or, are you talking about a software based implementation of such key effects?

----
Or, are you suggesting the editor should set colours on different layers? If so,  I'm not so sure of having pixel-based "colour" layers versus simply setting/picking colours on keys.

-----
"Profiles" are currently for basic key highlighting in games and applications. Granted, it's not easy to set a gradient of all the keys (for instance), which could be some extra UI options to generate them.

To keep things clear, I think we should call them **Key Profiles** and any custom / aesthetic or animated "profiles" **Custom Effect Profiles**.

**Comment by terrycain** [comment]
Effects per key would be software based. The daemon would have to support it. Until my new daemon is out I would hold off on thinking about this too much :wink:

**Comment by geordieF** [comment]
What I propose is that we render the effect on a canvas, `getImageData` that and  apply pixel colours to keys. It would be a polychromatic feature, not the daemon.

**Comment by lah7** [comment]
I'm afraid I can't see the practical side of this.for the moment, nor am I fully understanding what you mean by your idea of "effects". Thanks for your interest though.

The profile editor will be revisited once the new daemon comes along and allows per key "lighting effects". After that, we are ready for more fancy lighting editor and perhaps even a new editor for creating animated "effects profiles". :wink:
