### ISSUE TITLE
Version 0.3.x: ERROR:dbus.proxies

### ISSUE THREAD

**Issue by gsmithufl** [lah7/polychromatic#25]
On the latest version of Kubuntu I receive this error when starting the app from konsole. It's the first time I've played with it and I'm fairly new to linux so I don't know if it's a software center problem because I'm using KDE or otherwise. I tried the debian method for adding the app and it results in the same error.

> ERROR:dbus.proxies:Introspect error on :1.30:/org/razer: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
> Traceback (most recent call last):
>   File "/usr/bin/polychromatic-controller", line 1380, in <module>
>     app = Controller()
>   File "/usr/bin/polychromatic-controller", line 190, in __init__
>     self.devman = rclient.DeviceManager()
>   File "/usr/lib/python3/dist-packages/razer/client/__init__.py", line 25, in __init__
>     self._device_serials = self._dbus_devices.getDevices()
>   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
>     return self._proxy_method(*args, **keywords)
>   File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> ERROR:dbus.proxies:Introspect error on :1.30:/org/razer: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by lah7** [comment]
This is an error/bug related to the daemon - which this program interfaces with. It looks a bit similar to [this issue](https://github.com/GabMus/razerCommander/issues/8), but sadly there wasn't a solution. It seems it's properly installed, since Kubuntu and Ubuntu are Debian-based.

Which devices do you have? What do you see in the logs at `~/.razer-service/logs/razer.log`?

Does anything improve if you forcefully **kill** the service (using KDE's task manager) and starting it  fresh from the terminal?

    razer-service -v -F

**Comment by gsmithufl** [comment]
I killed the service and restarted with `razer-service -v -F` and it worked. However, it isn't recognizing my Mamba. I then killed it again and started the service regularly and it also worked (not recognizing Mamba). Perhaps having it running when I updated originally caused an issue? I checked the log and noticed the screensaver warnings but nothing else. 

I am using a Blackwidow Chroma and a Mamba Chroma. The Blackwidow is recognized. Anything else I can do to debug?

**Comment by lah7** [comment]
Mamba [should be supported](https://github.com/terrycain/razer-drivers#device-support) by the daemon - although support was added very recently. Which model? (Wireless, Wired, Tournament?)

**Comment by gsmithufl** [comment]
Mamba TE Wired. I guess I should explore the issues over there. Polychromatic looks great! I'm using it on the keyboard now.

**Comment by lah7** [comment]
Hmm, I have the exact same mouse. Saying that, I was given some experimental packages to test. I'm guessing @terrycain needs prodding to release some new packages with the new Mamba TE support. :smile:

**Comment by terrycain** [comment]
Yeah sorry. Needs a little work, should have package updates out by end of the week

**Comment by lah7** [comment]
Can confirm the latest packages (`1.0.10-0ubuntu1`) have support for the Mamba TE.
