### ISSUE TITLE
Imperator not shown in configuration utility

### ISSUE THREAD

**Issue by MinervaW1993** [lah7/polychromatic#27]
Razer-driver added support for Imperator 2012 but the configuration utility is not showing it. I looked at my /sys/bus/hid/drivers/razermouse and the mouse is already bidden to the razer driver (not hid-generic), but the configuration utility fails to recognize it.

**Comment by lah7** [comment]
The daemon is responsible for passing the devices that are attached to Polychromatic. Have you definitely got the latest daemon? Which distro are you using?

One way to check the daemon is working is to type these commands in `python3`:
```
import razer.client
a = razer.client.DeviceManager()
a.devices
```

You should see a list of devices, similar to this:
```
[<RazerKeyboard xxxxxx>, <RazerFirefly xxxxx>, <RazerDevice xxxxx>]
```

If it appears there, then it could be a bug with Polychromatic.
If it's not listed there, the daemon (or the version you're using) doesn't support the mouse, which is odd [as it should do](https://github.com/terrycain/razer-drivers#mouse) (or it might be a bug).

**Comment by MinervaW1993** [comment]
Reinstalled daemon & recognized. Thank you.
