### ISSUE TITLE
Error message at start (problem with setBrightness)

### ISSUE THREAD

**Issue by claell** [lah7/polychromatic#28]
With my Abyssus 2014 attached I got the following message (probably because the function is not supported by device): `polychromatic-controller crashed with dbus.exceptions.UnknownMethodException in _method_lookup(): org.freedesktop.DBus.Error.UnknownMethod: Unknown method: setBrightness is not a valid method of interface razer.device.lighting.brightness`

**Comment by lah7** [comment]
Looks similar to #28, I didn't realise the daemon doesn't all interface with brightness in the same way. I'll take a look when I get time.

**Comment by claell** [comment]
Thanks :+1:
