### ISSUE TITLE
Support for toggling logo for Razer Abyssus

### ISSUE THREAD

**Issue by claell** [lah7/polychromatic#29]
Currently there does not seem to be mouse/device specific options. For example my mouse does only support setting lighting on/off, but I cannot do this via Polychromatic right now.

**Comment by lah7** [comment]
Which mouse/device handles the brightness toggle differently? If you could provide the commands that the Python daemon would use for your device, that would be very helpful.

**Comment by claell** [comment]
I only know my device which handles it differently, there might be more.
I don't know, which command the daemon uses, maybe @terrycain knows that.

**Comment by lah7** [comment]
You could investigate by typing this into `python3`:
```
import razer.client as a
b = a.DeviceManager()
c = b.devices[0]         // Assuming it is the first device, type 'c' to list them all.
```

Then type `c.` followed by a **tab** to list everything that can be interfaced. `c.brightness` for my mouse outputs:
```
dbus.Double(100.0)
```

`c.brightness = 100` would set the brightness to 100%. Yours may require a `True` or `False` which if it does, this particular brightness issue can be solved quite easily.

**Comment by terrycain** [comment]
Heh. I'll have a look at this in the morning, think I know whats wrong.

**Comment by claell** [comment]
@lah7 I followed the steps you told me. Here is the output:
```
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import razer.client as a
>>> b = a.DeviceManager()
>>> c = b.devices[0]
>>> c
<RazerDevice PM1524119410828>
>>> c.
c._FX(                      c.__le__(                   c._available_features       c._type
c.__class__(                c.__lt__(                   c._capabilities             c._vid
c.__delattr__(              c.__module__                c._dbus                     c.capabilities
c.__dict__                  c.__ne__(                   c._dbus_interfaces          c.dedicated_macro
c.__dir__(                  c.__new__(                  c._drv_version              c.driver_version
c.__doc__                   c.__reduce__(               c._fw                       c.firmware_version
c.__eq__(                   c.__reduce_ex__(            c._get_available_features(  c.fx
c.__format__(               c.__repr__(                 c._has_dedicated_macro      c.has(
c.__ge__(                   c.__setattr__(              c._has_feature(             c.name
c.__getattribute__(         c.__sizeof__(               c._matrix_dimensions        c.serial
c.__gt__(                   c.__str__(                  c._name                     c.type
c.__hash__(                 c.__subclasshook__(         c._pid                      
c.__init__(                 c.__weakref__               c._serial                   
>>> c.brightness
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/razer/client/devices/__init__.py", line 178, in brightness
    return self._dbus_interfaces['brightness'].getBrightness()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getBrightness is not a valid method of interface razer.device.lighting.brightness
```

**Comment by terrycain** [comment]
What mouse is it again?

**Comment by claell** [comment]
Abyssus 2014 :)

**Comment by terrycain** [comment]
@lah7 the mouse only has the ability to turn a logo on and off

**Comment by terrycain** [comment]
Just for reference, this is all the methods the abyssus has.
![selection_013](https://cloud.githubusercontent.com/assets/1986397/18810789/c55b8e7c-8296-11e6-9b7a-f0d46dac9874.png)

**Comment by terrycain** [comment]
Have added to python library so now there is `python_device_object.fx.misc.logo` and `python_device_object.fx.misc.scroll` (when I get round to pushing). Will speak to @lah7, about the implementation but it all seems to work nicely on my test Abyssus :wink:.

**Comment by claell** [comment]
Thank you very much for your effort and sorry for causing it with my very simple mouse.

**Comment by terrycain** [comment]
@claell That's quite alright. And the aim is to support as much as possible, so if something doesn't work for one device then it probably means it doesn't work for others that share the same logic so it all helps.

**Comment by terrycain** [comment]
New packages are out. Update all, reboot and then the driver/daemon/library should be good. Then its down to @lah7 to add support.

**Comment by claell** [comment]
Alright. Seems like he already has added support for this in #28. Currently I have no access to my setup with the Abyssus (for around two weeks probably), but I will test as soon as I have.

**Comment by lah7** [comment]
@terrycain Thanks for the speedy updates!

@claell Nope, issue #28 is to prevent unsupported features from appearing, so attempting to set the brightness won't cause it to crash as the option isn't visible. I'm implementing support for toggling the logo as we speak. As I don't have the device to test, I am hoping it'll work without question. :ok_hand:

**Comment by claell** [comment]
Ok, thanks for clarification.

**Comment by claell** [comment]
I can confirm that now I get only a toggle button displayed in Polychromatic and toggling works as well. However it seems like the button shows off state when light is on. Is this a problem in Polychromatic or was something mixed up when creating the driver?

**Comment by terrycain** [comment]
I'll have a prod round the code my end and have a look.

**Comment by lah7** [comment]
It's likely to be Polychromatic, since none of the effects / current states are being tracked properly, so the slider always starts as "off". This is where issue #14 comes in.

Alternately, it could be the daemon, but I think it's working as it should, as it's just reading the true/false state of:

    device_object.fx.misc.logo

**Comment by claell** [comment]
@lah7 At first I thought the same, but it is also turning the light off when moving the switch to "on".

**Comment by terrycain** [comment]
@claell does it toggle the logo on and off just the ui doesn't work as it should?

**Comment by claell** [comment]
Yes.

**Comment by claell** [comment]
Everything is working as expected now. Thanks!
