### ISSUE TITLE
Polychromatic Controller and Tray Applet won't launch?

### ISSUE THREAD

**Issue by CryptCatZero** [lah7/polychromatic#30]
I'm a Linux newb, running Mint18. I downloaded and installed the terrycain-razer-drivers, and followed all the instructions step by step. I followed that with an install of Polychromatic Controller from the LinuxMint Software Manager. I click the software icon and nothing happens. I reboot. Try again. Nothing happens. No error messages or anything. Just nothing. 

Previously to this, I had attempted to run Polychromatic without installing the daemon (obviously, this didn't work, but) the software launched with an error message. Now it doesn't launch at all. 

I'm running on a first-gen Razer Blade Stealth. 

Please help?

**Comment by CryptCatZero** [comment]
To be more specific, I'm running Mint18, 64-Bit, Cinnamon. Any help you all can provide is super appreciated. Thanks.

**Comment by lah7** [comment]
Please check the daemon is definitely running. The software cannot interact with the devices without it. You can run the daemon from the terminal:

    razer-service -F -v

This will run it in the foreground, so you can see what the daemon is up to. Normally `razer-service` should just auto start when you login to your desktop. If you find it wasn't running, you may need to add a entry in **Start-up Applications**.

------------
Next, try opening Polychromatic from the terminal:

    polychromatic-controller

If there is a crash, this will be show some helpful output - please paste that here to help investigate.

----------
Usually, if the driver/daemon and Python libraries are not installed properly, the application will not run. It will try its best to catch errors and display a message. :wink:

**Comment by CryptCatZero** [comment]
Followed your instructions. This is what I was greeted with in the terminal:

cryptcat@cryptcat-Blade-Stealth ~ $ razer-service -F -v
Daemon already exists. Please stop that one.
cryptcat@cryptcat-Blade-Stealth ~ $ polychromatic-controller
Using relative path for translations.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 1380, in <module>
    app = Controller()
  File "/usr/bin/polychromatic-controller", line 190, in __init__
    self.devman = rclient.DeviceManager()
  File "/usr/lib/python3/dist-packages/razer/client/__init__.py", line 33, in __init__
    device = _RazerDeviceFactory.get_device(serial)
  File "/usr/lib/python3/dist-packages/razer/client/device.py", line 56, in get_device
    device = device_class.get_device(serial, vid_pid=device_vid_pid, daemon_dbus=daemon_dbus)
  File "/usr/lib/python3/dist-packages/razer/client/devices/keyboard.py", line 148, in get_device
    return device_class(serial, vid_pid=vid_pid, daemon_dbus=daemon_dbus)
  File "/usr/lib/python3/dist-packages/razer/client/devices/keyboard.py", line 128, in __init__
    self._update_capabilities(default_capabilities)
AttributeError: 'RazerBladeStealthKeyboard' object has no attribute '_update_capabilities'

**Comment by lah7** [comment]
It's a bug in the daemon for your particular device - @terrycain who writes the driver/daemon is aware of this and says he'll release an update in the next day or two.

Till then, hang tight for updates (as you have added the PPA, this will come through your software updater).

**Comment by CryptCatZero** [comment]
Thank you so much! Your speedy feedback is super appreciated. Loving Linux so far, and for this to be my first experience on GitHub, I'm loving it now even more. Take care!

**Comment by lah7** [comment]
Thanks - this is good too as you have uncovered a bug, as there should have been an error screen for the Controller when the daemon isn't running/working. I'll address that and close this issue when it's fixed.

**Comment by CryptCatZero** [comment]
When I didn't have the daemon installed, I did get an error screen that told me to check to make sure it was running and to try and run razer-service from the terminal. But, after I installed the proper files and restarted the computer, no error screen.
