### ISSUE TITLE
Sometimes crash on start

### ISSUE THREAD

**Issue by claell** [lah7/polychromatic#35]
Sometimes the tray applet fails to load after booting.
I get this message:
![bildschirmfoto vom 2016-10-08 09-58-28](https://cloud.githubusercontent.com/assets/6171135/19488315/92da771e-9566-11e6-816b-c0690b38455e.png)

**Comment by lah7** [comment]
There isn't enough details to why it crashed. My guess is that the tray applet loads before the daemon is initialised, which causes it to crash.

**Comment by claell** [comment]
Alright, thanks!
