### ISSUE TITLE
Razer Tartarus Chroma Profile Support

### ISSUE THREAD

**Issue by duapruis** [lah7/polychromatic#36]
Hi, today I got my Razer Tartarus Chroma that I bought since I found out of your project and @terrycain's  one. First of all thanks for all the effort and work you put into this.

The macro keys and profile options are greyed out  on the tray applet atm. The ones are:  Game Mode, Profiles, Enable Macro Keys, Change Primary/Secondary colors and on the top the first option Tartarus Chroma is also greyes out. Ofc this options aren't displayed on the configuration utility either.

I suppose this is because it hasn't been implemented yet? Or have I done something missed/done something wrong during the installation process? In case it hasn't been implemented, is there any other way around on the meantime?

Ps: Excuse my English...

Thanks.

**Comment by lah7** [comment]
Hi, thanks for your comments.

The Razer Tartarus Chroma is a keypad, which isn't entirely supported in Polychromatic at the moment, which is why some options are greyed out:

* **Game Mode** - keyboards only
* **Application Profiles** - keyboards only
* **Enable Macro Keys** - optional toggle for keyboards
* **Change Colours** - _not sure about that one...._ :thinking: 

So, sorry about that. There is nothing wrong with your installation. Some work will be needed to support profiles for keypads, which should basically need the co-ords and a vector image. For the colours, there is likely a logic bug, since yours is a "Chroma".

----------
In the tray applet, the first option is greyed to indicate the active device. If another device was selected from the **Devices** menu, (like the BlackWidow Chroma keyboard), then this would only enable the options if the device supports them. This data is passed from the daemon, which tells Polychromatic what the device is capable of.

You can see for yourself which devices your device supports by typing these commands in `python3` (from the terminal):

```
import razer.client
a = razer.client.DeviceManager()
b = a.devices[0]
b.capabilites
```

This is the output for the BlackWidow Chroma:
```
{'macro_mode_led': True, 'macro_mode_led_effect': True, 'lighting_breath_dual': True, 'lighting_ripple': True, 'macro_tartarus_mode_modifier': False, 'lighting_led_single': False, 'type': True, 'lighting_breath_single': True, 'lighting_breath_random': True, 'lighting_ripple_random': True, 'lighting_static': True, 'lighting_logo_te': False, 'lighting_scroll': False, 'lighting_logo': False, 'macro_logic': True, 'lighting_none': True, 'lighting_spectrum': True, 'lighting_logo_abyssus': False, 'brightness': True, 'firmware_version': True, 'name': True, 'lighting_reactive': True, 'serial': True, 'lighting_wave': True, 'lighting_pulsate': False, 'game_mode_led': True, 'lighting_led_matrix': True}
```

(The output of your device's capabilities would be helpful too)

**Comment by duapruis** [comment]
Oh I see, I had the feeling it was that but I just wanted to double check. Is there any way I could give you a hand with it then? Any way I could share with you the co-ords and a vector image? If that would help you and you plan on doing it (don't want to push you :V).

Everything I haven't listed there works, the colours work just fine except there is a missing option of "highlight what you press" thingy, not that I miss it tbh, it's just extra fancy looks nothing else.

This is my output of the commands you've posted:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RazerKeyboard' object has no attribute 'capabilites'

**Comment by lah7** [comment]
> Traceback (most recent call last):
> File "", line 1, in 
> AttributeError: 'RazerKeyboard' object has no attribute 'capabilites'

My bad, there was a typo. It should read **`capabilities`**.

---------------
>  Is there any way I could give you a hand with it then? Any way I could share with you the co-ords and a vector image?

These commands will allow you to experiment with co-ordinates:

    b.fx.advanced.matrix[row, column] = (red, green, blue)
    b.fx.advanced.draw()

Example:

    b.fx.advanced.matrix[0, 1] = (0, 255, 0)


This will give us the details needed to piece together a [SVG similar to the keyboard](https://github.com/lah7/polychromatic/blob/master/data/mapping/blackwidow-chroma-keyboard-layout.svg). The buttons need to be ID'd in a way so it can be manipulated by the program. If you'd like to create the SVG too, that's great. The co-ordinates will be enough to allow me to piece together Tartarus profile support within the next few days (hopefully).

I'll note down to look into the change colours option, as I think it's just a logic error as the daemon doesn't explicitly tell Polychromatic "_This device supports RGB_".

**Comment by terrycain** [comment]
Tartarus chroma can't do individual colours btw. But should all be in that capabilities dict

**Comment by duapruis** [comment]
The RGB colors work fine, terry is right, they can't do individual colors, I was talking about everything being with no lights and you pressed one and that particular one lighted up but I double checked and that's not the Tartarus Chroma, its the orbweaver (which is a keypad as well), so as for the lights everything works just fine :).

I'll post what you've posted me @lah7 asap.

**Comment by duapruis** [comment]
import razer.client
a = razer.client.DeviceManager()
b = a.devices[0]
b.capabilities

**OUTPUT:**
> 
{'lighting_pulsate': False, 'macro_mode_led': False, 'serial': True, 'macro_tartarus_mode_modifier': True, 'brightness': True, 'lighting_led_matrix': False, 'lighting_reactive': False, 'lighting_breath_random': True, 'lighting_static': True, 'lighting_ripple': False, 'macro_logic': True, 'macro_mode_led_effect': False, 'lighting_none': False, 'lighting_logo_te': False, 'lighting_spectrum': True, 'type': True, 'lighting_scroll': False, 'lighting_ripple_random': False, 'lighting_breath_single': True, 'firmware_version': True, 'name': True, 'lighting_wave': False, 'lighting_logo_abyssus': False, 'game_mode_led': False, 'lighting_led_single': False, 'lighting_logo': False, 'lighting_breath_dual': True}

**Comment by terrycain** [comment]
I'd suggest tracing the one in Razer synapse ;-) it gives you enough of a start

**Comment by duapruis** [comment]
Sadly I don't have a machine with windows atm and I tried to run Synapse under wine without no luck, not that it surprises me after seeing so many "garbage" status on WineHQ.

I'll try my best with wine and inkscape *fingers crossed*.

**Comment by duapruis** [comment]
There we go... If you think there is something missing just tell me, I don't know what the right keys are called so feel free to tell me or edit the SVG. If you don't think is good enough I can give it a second try.

https://www.dropbox.com/s/i2vmkawj2j4uxkz/drawing-1.svg?dl=0

**Comment by terrycain** [comment]
Pretty sure the key names are fine but you be missing the dpad on the right inbetween 2 thumb buttons

https://www.google.co.uk/search?q=tartarus+chroma&espv=2&biw=1920&bih=901&source=lnms&tbm=isch&sa=X&ved=0ahUKEwie3-3sx-bPAhVLp48KHV28D1IQ_AUICCgD#imgrc=NzBlYWEa3mXsLM%3A

**Comment by duapruis** [comment]
Oh yeah I know, I even added a green border to those keys, I just don't know how to enum them, do they have an specific name/id?

**Comment by terrycain** [comment]
Yeah, ill post it later

**Comment by duapruis** [comment]
Thanks.

**Comment by duapruis** [comment]
@lah7 do you need more input information about the Tartarus Chroma that I can give you and I forgot?

**Comment by terrycain** [comment]
```
    '1': (0, 0),
    '2': (0, 1),
    '3': (0, 2),
    '4': (0, 3),
    '5': (0, 4),
    'UP': (0, 6),

    '6': (1, 0),
    '7': (1, 1),
    '8': (1, 2),
    '9': (1, 3),
    '10': (1, 4),
    'LEFT': (1, 5),
    'RIGHT': (1, 7),

    '11': (2, 0),
    '12': (2, 1),
    '13': (2, 2),
    '14': (2, 3),
    '15': (2, 4),
    'THUMB': (2, 5),
    'DOWN': (2, 6),
    'MODE_SWITCH': (2, 7)
```

Ignore the `(X, X)` 

Basically the top button is thumb, then dpad then mode_switch

**Comment by duapruis** [comment]
Thanks, I'll update the picture tomorrow.

**Comment by lah7** [comment]
Thank you both. Now I've got the data needed to implement this, I was waiting on @duapruis to update the vector image. Are you still doing this or shall I take it from here? (It looks great by the way!)

Since I don't actually have the device, I'll need to rely on your help to test it. :ok_hand:

**Comment by duapruis** [comment]
@lah7 Yes, sorry, I've been very busy lately, I'll update it asap (I'll probably update it tomorrow night GMT+1 time) sorry about that!

**Comment by duapruis** [comment]
That's it, I'm not a 100% sure that this are the correct positions but I suppose THUMB is were the thumb normally rest and MODE SWITCH the other one, well, if I'm wrong I can always change it easily, once again, sorry for the late.

https://www.dropbox.com/s/dk56c3asqyt4onz/drawing-2.svg?dl=0

**Comment by lah7** [comment]
No problem for the lateness. I'll try and get the profile support implemented as soon as I can after finishing some other changes first. I'll let you know when there's something new to report or it's ready to test.

**Comment by lah7** [comment]
Unfortunately, it looks like there were some crossed wires here.

> Tartarus chroma can't do individual colours btw. But should all be in that capabilities dict

I was believing that the Tartarus was like a keyboard and supported per-key lighting (but were all the same colour) utilising the same code. Turns out this is not true... at least for now.

Sorry about that. Once the daemon supports this for keypads, then profiles can be implemented in Polychromatic. :smile: Till then, the application still needs some re-structuring for v0.4.0.

**Comment by duapruis** [comment]
Oh, OK. Well thanks any ways for all your time! I found a project called "Keyboarding Master" by Michael Speth  that support key configuration for many gamepads, even a razer keyboard, so at least I can use it on the meantime :). I'll post you the link just in case you are curious: https://sites.google.com/site/keyboardingmaster/devices
