### ISSUE TITLE
Duplicate actions (WebKitGTK bug)

### ISSUE THREAD

**Issue by lah7** [lah7/polychromatic#39]
This is just noting a known (but irritating) issue with the newer versions of `webkit2gtk`.

You may notice that clicks or actions happen twice, or starts spamming "Unimplemented command" in the terminal.

**Package(s) affected:**
* Ubuntu - `gir1.2-webkit2-4.0`
* Arch - `webkitgtk`

**Version(s) affected:**
* Problematic with 2.14 onwards.
* 2.12 and below are not affected -- however, Ubuntu 16.04 users have recently have updates for 2.14.

----------
Here is a bug report on Launchpad as this affects web-based applications in general that rely on this library: https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/1633736

**Comment by z3ntu** [comment]
There's no package in Arch called `webkitgtk` 😜 
```
luca@g550jk ~> pacman -Q webkit2gtk 
webkit2gtk 2.14.2-2
luca@g550jk ~> pacman -Q webkitgtk2 
webkitgtk2 2.4.11-3
```

**Comment by lah7** [comment]
> There's no package in Arch called `webkitgtk`

Maybe not in the main repositories, but [it looks like there is in the "extra" repository](https://www.archlinux.org/packages/extra/x86_64/webkitgtk/) (as linked in the README).

**Comment by z3ntu** [comment]
I don't have that installed though; and polychromatic works...

**Comment by lah7** [comment]
There will be a package that provides GObject introspection data for WebKit2. In Ubuntu, that's `gir1.2-webkit2-4.0`. I'm guessing there will be one similar for Arch?

**Comment by lah7** [comment]
This has been addressed in https://github.com/lah7/polychromatic/commit/cbde66e9cc84d86485c4f8b8c57b3b5aa0dceb9c (and the latest update - [v0.3.6](https://github.com/lah7/polychromatic/releases/tag/v0.3.6))
