### ISSUE TITLE
Application Errors on Startup "TypeError: Can't convert 'NoneType' object to str implicitly"

### ISSUE THREAD

**Issue by CorneliaXaos** [lah7/polychromatic#40]
So.. this might be because I don't have a device that's supported by the daemon yet (I have the Diamondback Chroma).. but I thought I'd report this error that happens on launch of the polychromatic-controller:

```
cornelia@Xaos-OryxP:~$ polychromatic-controller       
Using relative path for translations.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 125, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 445, in page_loaded
    self.refresh_device_list()
  File "/usr/bin/polychromatic-controller", line 1393, in refresh_device_list
    app.update_page('#' + selected_ui, "addClass", "active")
TypeError: Can't convert 'NoneType' object to str implicitly
```

I figure, even if the user doesn't have any daemon supported devices the application probably shouldn't error like this.. If anything, it should notify the user of missing devices, etc.

**Comment by lah7** [comment]
Thanks for reporting. Indeed, there should be a "No devices found" screen, but some logic bugs were in the way. It's now fixed in the latest `master`. :+1:
