### ISSUE TITLE
Error message with DeathAdder and Abyssus devices

### ISSUE THREAD

**Issue by claell** [lah7/polychromatic#43]
Now that https://github.com/terrycain/razer-drivers/issues/67 seems to be fixed I went ahead and wanted to try Polychromatic. Unfortunately Ubuntu shows the following error message:
![bildschirmfoto vom 2016-12-21 12-29-28](https://cloud.githubusercontent.com/assets/6171135/21387715/2e12c792-c779-11e6-84de-c96d5a6e45d6.png)

Also toggling the light on the Abyssus 2014 does not work. So maybe this is related.

**Comment by MrBlaise** [comment]
Same here

**Comment by claell** [comment]
@MrBlaise Which Razer device do you use?

**Comment by MrBlaise** [comment]
DeathAdder Chroma

**Comment by claell** [comment]
This bug is no longer happening for me after the recent update, however I have a new issue: #50

**Comment by lah7** [comment]
Hang tight! Support for the DeathAdder (and devices that function similarly like Abysuss) is the literally in development.

The interface will get a bit of a visual refresh to cater for how this device handles lighting effects (this device is split into `logo` and `scroll_wheel`, whereas other mice use the main FX function). This will be out in the next release (v0.3.7).

Sorry it's taken so long, it's finally coming!

**Comment by lah7** [comment]
[Support has been (finally!) been added for these devices](https://github.com/lah7/polychromatic/commit/670e084ff8810fb50439af1a2607063b95336448) in the latest `master` code.  :+1:

**Comment by claell** [comment]
Works for me, thanks!
