### ISSUE TITLE
Multiple Devices being affected

### ISSUE THREAD

**Issue by sranger** [lah7/polychromatic#44]
Now that I have the daemon finding my devices under Ubuntu 16.10; I'm noticing that when I change the settings for my keyboard or mouse the other device receives the settings as well. If you need any other debug info or if this is a daemon issue, let me know.

**Comment by jpfoote** [comment]
Have you looked in Preferences/Daemon to make sure "Sync Effects to All Devices" is not selected?

**Comment by sranger** [comment]
Oh awesome! Didn't even realize that was a thing; sorry for the issue clutter. Thanks for the input!
