### ISSUE TITLE
When waking from sleep (lights out) first key stroke is dropped

### ISSUE THREAD

**Issue by jpfoote** [lah7/polychromatic#45]
BlackWidow Chroma  Ubuntu 16.04 Linux.  

The system is not locked or asleep, keyboard lights go out after a short duration. When starting to type form this state the first key pressed does not make it to the dialog such at a browsers URL input dialog.

This does not occur all of the time but often enough to be a pain. Did not have this issue before installing Linux drivers and software for Razor keyboards. The work done in this project has been outstanding!  Thank you and I am willing to provide any logs or documentation you might require.

**Comment by lah7** [comment]
Hi, thanks! This repository is solely for the Controller/Tray Applet application, any underlying problems are most likely to be driver or daemon related which goes beyond my knowledge.

[You should raise an issue on the actual driver/daemon repository instead](https://github.com/terrycain/razer-drivers) and post the output of a clean `~/.razer-service/logs/razer.log` for the author to take a look at.

That said, I have the BlackWidow Chroma on Ubuntu MATE 16.04, and haven't experienced any problems after waking up from suspend. The lights going off might be related to the screensaver feature, which can be turned off in the daemon settings tab.
