### ISSUE TITLE
Depends gir1.2-gtk3.0

### ISSUE THREAD

**Issue by Thellior** [lah7/polychromatic#49]
Hello,

I'm trying to install your driver but it's failing on the dependency gir1.2-gtk3.0 and cannot be installed. I enabled the universe repository and updated it. Still getting the error. I found out that gir1.2-gtk-3.0 is installed but that's with a dash. So i'm kinda stuck.

Someone got a tip on this one?

Error:
razer-daemon : Depends: gir1.2-gtk3.0 but it is not installable

Ubuntu 16.04

Thanks in advance

**Comment by lah7** [comment]
Hi, you're right, there is a typo in the `razer-daemon` package. [I've committed a fix](https://github.com/terrycain/razer-drivers/commit/4d3b0f43deb191e67e99363c5317bf2ef51e179a). Thanks for spotting that!

@terrycain will re-release the packages later today.

**Comment by Thellior** [comment]
@lah7 Thanks for the fast response and fix :)
