### ISSUE TITLE
Failed to toggle logo message

### ISSUE THREAD

**Issue by claell** [lah7/polychromatic#50]
I just tried Polychromatic again after the update and now I get the message "Failed to toggle logo for Razer Abyssus 2014." when I toggle the logo.

**Comment by lah7** [comment]
I think the daemon may have changed something since this was initially written, but now with https://github.com/lah7/polychromatic/commit/670e084ff8810fb50439af1a2607063b95336448 this is fixed and working again.

**Comment by claell** [comment]
Is this already in the PPA?

**Comment by lah7** [comment]
Not yet, changing the colours is not particularly stable, so I'd like to get that patched up before a new release. You can give it a test by doing:

    git clone https://github.com/lah7/polychromatic.git
    cd polychromatic
    ./polychromatic-controller

**Comment by claell** [comment]
Ok. I will wait until it is in the PPA then, since I am a bit busy atm :)

**Comment by claell** [comment]
I can confirm this is fixed for me. Thank you!
