### ISSUE TITLE
Main window stays blank

### ISSUE THREAD

**Issue by gmemstr** [lah7/polychromatic#51]
`Linux Stealth 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux`

When loading the program, the window remains blank but the console says the application is ready. Have double checked all requirements are installed and working.

```
Debug verbose enabled.
Using relative path for translations.
Initialised WebKit2.
Window icon set from /usr/share/ path.
Program Scale Set: 1.0
Initialised Window.
Loading Daemon...
Gathering Devices...
 -- Found: Razer Blade Stealth (Late 2016)
Loading Application Profiles...
Application Ready.
```
![Screenshot](https://cloud.githubusercontent.com/assets/1878840/22091808/d690d4d2-ddad-11e6-919d-8fba928451e0.png)

**Comment by gmemstr** [comment]
Update: It seems a second reboot fixed it. Odd, unsure if it's something I did or just magic.

**Comment by lah7** [comment]
Most likely that WebKit2 or GTK didn't initialise the display properly. How most odd. Glad to hear it's working again!
