### ISSUE TITLE
Tray icons for Plasma desktop

### ISSUE THREAD

**Issue by aldy-art** [lah7/polychromatic#52]
Hi, I don't know where to share this but I did two icons (light/dark) for polychromatic tray. I did this icons for better visual integration with my plasma desktop. I used the keyboard device icon from Breeze icon theme but added some colors from Breeze color palette.

PS: Sorry for my bad English.

[breeze-tray-icons.zip](https://github.com/lah7/polychromatic/files/720655/breeze-tray-icons.zip)

**Comment by lah7** [comment]
Thanks for contributing. :+1:  I'll add them to the application to show as default when running under KDE.
