### ISSUE TITLE
ripple not working

### ISSUE THREAD

**Issue by nickdesaulniers** [lah7/polychromatic#53]
thanks for making this set of utilities.  It works quite well.  I'm having an issue with Ripple.  When I set it, it doesn't appear to work, and in my `dmesg` I see:

```
[  216.116540] razerkbd: Command not supported. Start Marker: 05 id: ff Num Params: 46 Reserved: 03 Command: 0b Params: ff04001500ff0000ff0000000000ff00 .
```

I don't think this is unique to this project though, as I see it in [RazerCommander](https://github.com/GabMus/razerCommander/issues/22), too.  Should I move this to [the driver's project](https://github.com/terrycain/razer-drivers)?

**Comment by nickdesaulniers** [comment]
https://github.com/terrycain/razer-drivers/issues/166

**Comment by z3ntu** [comment]
Then this & the issue in razerCommander should be closed as it's a driver issue :)
