### ISSUE TITLE
crash upon boot

### ISSUE THREAD

**Issue by nickdesaulniers** [lah7/polychromatic#54]
I had installed polychromatic on an 4.10rc4 kernel, then booted a 4.10rc3 kernel into Ubuntu 16.10 (not sure if that would make a difference, but those were my steps to reproduce).

Upon boot, I got a dialog about an internal issue.  It looks like polychromatic-tray-applet crashed with a stack trace.  Sorry for the picture, but I could not copy the trace out of the dialog.

![trace](https://cloud.githubusercontent.com/assets/1823839/22186743/5b7e6a0c-e0af-11e6-8095-51a4bb3921e5.png)

**Comment by nickdesaulniers** [comment]
```sh
nick@nick-Blade-Stealth:~$ polychromatic-tray-applet 
Using "/usr/share/locale/" or falling back to "en_US" for translations.

Tray applet couldn't be initalised!
Reason: No devices found.
Reloading in 60 seconds.

Tray applet couldn't be initalised!
Reason: No devices found.
Reloading in 60 seconds.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 721, in <module>
    indicator.setup()
  File "/usr/bin/polychromatic-tray-applet", line 276, in setup
    self.active_device_status.set_label(devlist[0].name)
IndexError: list index out of range
```

**Comment by z3ntu** [comment]
Looks like #46
