### ISSUE TITLE
issue after waking from suspend

### ISSUE THREAD

**Issue by nickdesaulniers** [lah7/polychromatic#55]
may be a driver issue again, happy to move the issue if so.  After waking from suspend, I'm seeing the following errors:

```sh
nick@nick-Blade-Stealth:~$ polychromatic-controller 
ERROR: Exception: org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/razer_daemon/dbus_services/dbus_methods/all.py", line 63, in get_device_name
    with open(driver_path, 'r') as driver_file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.2/0003:1532:0220.0003/device_type'

ERROR: Could not connect to the Daemon Device Manager!
```

**Comment by lah7** [comment]
Yeah, it's a driver issue / daemon crash. This happens to me sometimes, the workaround is to restart the daemon.

**Comment by nicman23** [comment]
hey i know this is an old one but i am having this in a blackwidow 2016 and need to set color green for my keyboard to lit up after suspend.

is that a openrazer bug or polychromatic one

**Comment by lah7** [comment]
@nicman23 Devices missing after suspend would be an OpenRazer issue - but is your issue the same as this old one?

For you, it sounds like the OpenRazer feature which turns off the brightness on suspend / lock screen, turn it off in this file: `~/.config/openrazer/razer.conf` and restart the daemon:

    openrazer-daemon -r
