### ISSUE TITLE
polychromatic can't connect to Daemon Device Manager

### ISSUE THREAD

**Issue by Whanyerak** [lah7/polychromatic#57]
Hey ! I'm searching an issue to my problem but I'm unable to find one...
I would like custom my keyboard (I'm on a Razer Blade Stealth 2016) but when I try to start polychromatic I got this error message : 
________________________________________________
ERROR: Daemon Not Found.
ERROR: Could not connect to the Daemon Device Manager!
________________________________________________

I installed the razer_drivers as recommended and the daemon is running.
I tried to stop and restart the Daemon "razerd" but I got the same result.

I'm on Arch (Antergos) and I'm using a Razer Blade Stealth (128Go QHD 2016).

If someone has an issue, I would be really happy to know it !

Thank you in advance for your attention.

**Comment by lah7** [comment]
Hi. `razerd` isn't the daemon, the process should be `razer-service`. It could be possible you have the wrong (or an old) one installed.

What is the output of this?

    razer-service -F

If this results in a "command not found", this would be why.

This isn't a problem specific to Polychromatic, so there's not much I can do here. Please check that you have the [`razer-driver-meta`](https://aur.archlinux.org/packages/razer-driver-meta/) package installed on your Arch installation. [See the driver/daemon's installation page for more details](http://terrycain.github.io/razer-drivers/#arch).

**Comment by Whanyerak** [comment]
Ok I had a problem with python-six now it's fine thank you !
I can open the polychromatic-controller, I have a back window but at least I can change my keyboard configuration with the little icon in the system tray !

Thank you so much,
All my sympathy.
