### ISSUE TITLE
polychromatic-controller not detecting razer-service daemon

### ISSUE THREAD

**Issue by munchluxe63** [lah7/polychromatic#58]
**Edit: digging deeper, it seems there's an unresolved dependency,** 
>`ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory`

After starting the daemon, then polychromatic-controller, polychromatic is unable to detect the daemon:
>Daemon Not Installed
>Polychromatic requires the daemon, but it could not be imported. Please check the Razer drivers, daemon and Python library are installed.

I've also tried restarting the daemon from polychromatic gui; it restarts the service, but still does not detect it.

Installation:
>`git clone https://aur.archlinux.org/razer-drivers.git; and cd razer-drivers`
>`makepkg -sri`
>`sudo gpasswd -a daniel plugdev`
>`git clone https://aur.archlinux.org/polychromatic.git; and cd polychromatic`
>`makepkg -sri`

Running the daemon, and polychromatic
>`razer-service -vF`
>`polychromatic-controller -vv`

Logged output:
[log_polychromatic.txt](https://github.com/lah7/polychromatic/files/738069/log_polychromatic.txt)
[log_razer-service.txt](https://github.com/lah7/polychromatic/files/738070/log_razer-service.txt)

dkms module, python module, and daemon are installed:
>`daniel@dinovaldo ~> dkms status`
>`razer_chroma_driver, 1.0.0, 4.9.0-ARCH, x86_64: installed`
>`razer_chroma_driver, 1.0.0, 4.9.6-1-ARCH, x86_64: installed (original_module exists)`

>`daniel@dinovaldo ~> python`
>`Python 3.6.0 (default, Jan 16 2017, 12:12:55) `
>`[GCC 6.3.1 20170109] on linux`
>`Type "help", "copyright", "credits" or "license" for more information.`
>`>>> import razer_daemon`
>`>>> razer_daemon`
>`<module 'razer_daemon' from '/usr/lib/python3.6/site-packages/razer_daemon/__init__.py'>`

>`daniel@dinovaldo ~> file /usr/bin/razer-service `
>`/usr/bin/razer-service: Python script, ASCII text executable`

Arch linux, kernel version 4.9.6-1-ARCH

**Comment by lah7** [comment]
> Edit: digging deeper, it seems there's an unresolved dependency,
>
> `ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory`

Good find. One thing to note, in your `python` example, the daemon interface is actually provided in `razer.client`, not `razer_daemon`.

If you happen to find the package responsible for providing this file, @z3ntu can update the `razer-drivers` package to include that missing dependency for Arch.

**Comment by z3ntu** [comment]
`libgfortran.so.3` is provided by either `gcc-libs` or `gcc-libs-multilib`... But that package should be installed anyways as it is required by 1. a huge amount of packages and 2. it's required by gcc (and gcc is in the base-devel group you should have installed anyways). But I can add the dependency nevertheless

**Comment by munchluxe63** [comment]
Turns out I'd actually built GCC from source at some point for some reason, and so it was missing some statically linked libs, namely libgfortran.

Downgrading it from the main repository has fixed it.
