### ISSUE TITLE
Keep tray applet alive in the 'Retry' loop

### ISSUE THREAD

**Issue by z3ntu** [lah7/polychromatic#62]
If no devices are found, it waits 60 seconds and then retries. During that, the tray applet vanishes and is created again very shortly after (0.25 seconds or so) which is quite annoying because the taskbar gets resized when it's removed & created 👍

**Comment by lah7** [comment]
The tray applet quite literally "respawns" its process, which causes it to momentarily disappear. Some revamp work is needed for the poor old tray applet.

**Comment by lah7** [comment]
Fixed! The new tray applet in [v0.3.8](https://github.com/lah7/polychromatic/releases/tag/v0.3.8) no longer loops like this anymore. :+1:
