### ISSUE TITLE
Polychromatic Controller shows a completely black window

### ISSUE THREAD

**Issue by TheNavigat** [lah7/polychromatic#67]
Window is completely black. The tray works perfectly, but the controller shows just a completely black screen. It's installed using the PPA here, https://terrycain.github.io/razer-drivers/#ubuntu.

Here's the output of `polychromatic-controller -vv`

```
Debug verbose enabled.
Using relative path for translations.
Initialised WebKit2.
Window icon set from /usr/share/ path.
Program Scale Set: 1.0
Initialised Window.
Loading Daemon...
Gathering Devices...
 -- Found: Razer Blade Stealth (QHD)
Loading Application Profiles...
Application Ready.
```

![screenshot from 2017-03-15 22-08-49](https://cloud.githubusercontent.com/assets/4323539/23968588/01a2b5a6-09cc-11e7-82d4-af0e3b9516ca.png)

I'm running the application using Razer Blade late 2016 edition. GPU running Polychromatic is Intel® HD Graphics 530 (Skylake GT2). Operating system is Ubuntu 16.04 LTS.

Apparently someone else had the same issue (https://github.com/lah7/polychromatic/issues/51), but a second reboot doesn't fix it here.

**Comment by lah7** [comment]
Looks like you're running Ubuntu, which release?

Unfortunately, from what I've known of this issue with another application -- the **WebKit2** library spawns a process but had crashed (`WebKitWebProcess`) early on. :disappointed: 

It would be good to know what exactly is causing this as another app I maintain [suffers from this for a handful of users too](https://ubuntu-mate.community/t/welcome-screen-and-software-boutique-screens-are-blank/10513) -- I suppose it'll work eventually after multiple tries... why it does this on a handful of systems I don't know. :confused: 

If you can catch an error report, that would be handy, as this bug won't affect just Polychromatic.

**Comment by TheNavigat** [comment]
Ubuntu 16.04 LTS.

I tried `tail -f /var/log/syslog` as I ran the application, that was the result.

`Mar 16 00:10:54 Eark kernel: [   55.836180] WebKitWebProces[3743]: segfault at 0 ip 00007f38195a6385 sp 00007f37ae1fe1f8 error 4 in libc-2.23.so[7f3819459000+1bf000]`

If you need a more comprehensive error report you'll need to guide me through how to obtain one.

**Comment by TheNavigat** [comment]
Also, in my case, the problem is consistent. It doesn't work, no matter how many times I reboot, and no matter how many times I try. It always fails.

**Comment by lah7** [comment]
The line in `syslog` is helpful, thanks. Are you running `i386` or `amd64`?

The `libc-2.23.so` library could potentially be a problem on your system - something could have possibly "gone bad" with them. What do you get when you checksum the affected library in a terminal:

```
md5sum '/lib32/libc-2.23.so' '/lib/i386-linux-gnu/libc-2.23.so' '/lib/x86_64-linux-gnu/libc-2.23.so' 
```

As you're on Ubuntu 16.04 LTS as I am, assuming you're on 64-bit and everything is up-to-date, the hashes should match with mine:

```
5221435a058b204c3616b10dc7d7e6d0  /lib32/libc-2.23.so
843f3b0c7e61e84038fca6f0ad056a34  /lib/i386-linux-gnu/libc-2.23.so
a3e78b9d154d9d0936d3a1fda1743479  /lib/x86_64-linux-gnu/libc-2.23.so
```

-------

You could try re-installing the `libc6` and `webkit2` library, in case it _**is**_ faulty:

    sudo apt install --reinstall libc6:amd64 libc6:i386
    sudo apt install --reinstall gir1.2-webkit2-4.0 gir1.2-javascriptcoregtk-4.0 libwebkit2gtk-4.0-37

Otherwise, this may be something a bit deeper.

**Comment by TheNavigat** [comment]
I'm running amd64. `/lib32/libc-2.33.so` doesn't exist. `/lib32` doesn't exist. `/lib` and `/lib64` do.

```
➜  /lib
for file in $(find . | grep libc-2.23.so)
do
echo $(md5sum ${file})
done

843f3b0c7e61e84038fca6f0ad056a34 ./i386-linux-gnu/libc-2.23.so
a3e78b9d154d9d0936d3a1fda1743479 ./x86_64-linux-gnu/libc-2.23.so
```

**Comment by TheNavigat** [comment]
I updated my system (hadn't run any updates for some time) and ran the controller again and now it works. Spooky...

**Comment by lah7** [comment]
Unfortunately, there is nothing Polychromatic can do, as it is a problem one of the libraries on the system (that's causing WebKit to crash)... I'm not sure how this could be debugged.

Thanks for reporting back, glad that it's working. :+1:
