### ISSUE TITLE
In KDE in the tray applet not showing icon

### ISSUE THREAD

**Issue by DAVIDhaker** [lah7/polychromatic#68]
Workable a tray applet without icon. (Right of the cloud icon.)

![screenshot_20170321_142409](https://cloud.githubusercontent.com/assets/23550085/24145425/195b537c-0e42-11e7-884d-f5b13088dc15.png)

**Comment by lah7** [comment]
Luckily, the tray applet is being overhauled for the next release, which should resolve this issue.

If you go to the Preferences (in the Controller) → Tray Applet tab -- are you able to set a different icon?

**Comment by z3ntu** [comment]
Works for me... KDE Plasma 5.9.4 on Arch.

**Comment by lah7** [comment]
[v0.3.8](https://github.com/lah7/polychromatic/releases/tag/v0.3.8) has been released, the tray icon should be more reliable now.

**Comment by DAVIDhaker** [comment]
I upgraded, but no results.

If i run /usr/bin/polychromatic-tray-applet by sudo - icon shows, but not works *1. If i just run, works all except icon


1 - ERROR: Daemon isn't running or crashed.
Exception: Could not connect to daemon

(polychromatic-tray-applet:5821): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by z3ntu** [comment]
What distro are you using?

**Comment by DAVIDhaker** [comment]
Ubuntu 16.04 x64 with KDE.

**Comment by KayEss** [comment]
The KDE icon works fine on my machine:

    $ lsb_release -a
    LSB Version:    core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.10
    Release:        16.10
    Codename:       yakkety

Left clicking does nothing, but right clicking brings up the context menu.

**Comment by DAVIDhaker** [comment]
But for me - no.

$ lsb_release  -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	        16.04
Codename:	xenial

**Comment by lah7** [comment]
Sorry, I can't replicate this -- I tried on Kubuntu 16.04 and 16.04.2 and the icon works as expected.

The lack of left clicking may be a limitation of KDE (which is Qt based after all) or simply because it's only a context menu. I had an attempt at something with 458b912485e2d3b96ce94444fc0220a8b747735c but no success.
