### ISSUE TITLE
Custom effect

### ISSUE THREAD

**Issue by zskamljic** [lah7/polychromatic#72]
It would be nice if this software would have a "custom" option to create a custom lighting effect, similar to what razer comander has

**Comment by lah7** [comment]
"Custom effects" as in **specifying colours for keys** already exists, but it's called **Application Profiles**. 

This will appear for keyboards that support individual key lighting (at the moment -- this will expand to mice and the Firefly in the next major release)

I checked `razerCommander`, and they both do the same thing.
