### ISSUE TITLE
Question: Possible pull request for Logitech support

### ISSUE THREAD

**Issue by CReimer** [lah7/polychromatic#73]
I read about Polychromatic on OMGUbuntu and it looks really nice. There's only one problem. My whole setup is Logitech G based.

Keyboard: G910
Mouse: G502

Under which circumstances would you accept a pull request which adds support for Logitech hardware?
And if you do, where is the best place to start.

There's a tool called g810-led which supports almost all Logitech keyboard with RGB lighting and I already tested its pipe mode with python. This works quite well. So what's necessary to connect this to polychromatic.

Thanks.

**Comment by lah7** [comment]
Unfortunately, Polychromatic is heavily designed around the ["@terrycain" Razer daemon](https://github.com/terrycain/razer-drivers) and its functions, so it would be **very** messy to suddenly add in a completely different daemon/tool to manage an entirely different set of devices. :disappointed: 

For the moment, I'd prefer Polychromatic to stay focused on Razer products, as I've yet to build new features that's been pending for months. Eventually I'd like the application will be more modular to a point it's in a better position to easily add non-Razer devices, but it would be a lot of work. :sweat: 

It's not feasible at the minute, but thanks anyway. We would benefit with a Linux standard for RGB keyboards -- one daemon that fits all vendors.
