### ISSUE TITLE
Donate option for the Developers

### ISSUE THREAD

**Issue by Wolfizen** [lah7/polychromatic#75]
I love supporting developers of open-source projects that I use every day, and this is one of them. I use the polychromatic controller and the dkms drivers every day. The software is arguably more well polished and useful than actual Razer products.

I am suggesting that a donate link be available on the project readme. I personally would love to donate :D

**Comment by lah7** [comment]
Thanks! Glad you like the software, rest assured it's not finished yet. :smile:

[I've updated the README with the details](https://github.com/lah7/polychromatic#donations), so feel free, and thank you! I wish I had more time in the world so I can continue improving my open source projects at a faster pace. :ok_hand:

**Comment by Wolfizen** [comment]
👍
