### ISSUE TITLE
Keyboard (bw te) not working at all

### ISSUE THREAD

**Issue by Stella44** [lah7/polychromatic#76]
Quiting the program doesn't do anything at all neither does quiting the daemon. What the fuck happened? Other devices work perfectly...

**Comment by lah7** [comment]
I don't know, but it's not clear if you can't physically use the keyboard anymore or setting effects/brightness for that keyboard is no longer working.

It's not a UI issue, as this app only interacts with the daemon (which has recently been updated). Please [raise an issue on the driver/daemon repo](https://github.com/terrycain/razer-drivers/issues) clearly stating which distro and desktop environment you're using and paste the logs from the daemon and `dmesg`.
