### ISSUE TITLE
Failed to set/change brightness for razer naga 2014

### ISSUE THREAD

**Issue by kdb424** [lah7/polychromatic#77]
Saw that support was just recently added, and thought I'd give it a shot as I wanted to turn everything off. Also have a Tartarus Chroma that is working just fine on this. Looking for suggestions, and can report on anything you need.

Arch linux, fully up to date as of posting.
python-razer-git
razer-daemon-git
razer-driver-dkms-git
razer-driver-meta
polychromatic-git

lsusb | grep '1532:'           
Bus 003 Device 007: ID 1532:0040 Razer USA, Ltd 
Bus 003 Device 006: ID 1532:0208 Razer USA, Ltd 

On git versions as support was just added, though tried the stable versions with absolutely no difference.

**Comment by lah7** [comment]
Ah, the Razer Naga... the one with 3 light sources.

1. Which light sources do not work? (Circle / Scroll Wheel / Logo)?
2. Is this mouse one where LEDs can only be turned on/off, or can its brightness be changed?

Please print me the output by typing these commands into `python3`:

```
import razer.client
a = razer.client.DeviceManager()
a.devices                         // Lists your devices
b = a.devices[0]                  // Assuming Naga is the first one
b.capabilities
```

Try changing the brightness from here too -- Polychromatic uses the same functions. This will highlight a possible issue with the daemon if they fail for some reason.

```
b.brightness = 100
b.fx.misc.logo.brightness = 100
b.fx.misc.scroll_wheel.brightness = 100
```

Depending on how the lights behave, these might be `True` or `False`, or use the `.active` function instead.

**Comment by kdb424** [comment]
This is in fact the one with 3 light sources. Here is the output of what you had asked run in ipython (better output and debugging IMHO), with absolutely no changes to the lighting of the mouse after running, and one error.

https://pastebin.com/RmfLwfVE

**Comment by lah7** [comment]
Thanks, so this device only supports on/off brightness and introduced a new `backlight` function I've not seen before.

Please can you confirm this works?

```
b.backlight = True
b.fx.misc.logo.active = True
b.fx.misc.scroll_wheel.active = True
```

(Or `False` to turn them off)

`b.backlight` is just a guess, if it's not that, press Tab after `b.` to list all functions.

**Comment by kdb424** [comment]
In [12]: b.
            b.brightness       b.dpi              b.fx               b.max_dpi          b.razer_urls       
            b.capabilities     b.driver_version   b.has              b.name             b.serial           
            b.dedicated_macro  b.firmware_version b.macro            b.poll_rate        b.type    

That's what I have access to. None of what I poked around at made a difference. Driver issue possibly? I have tried to look for firmware updates for the device and it seems up to date, so that one can be ruled out.

**Comment by lah7** [comment]
Ah, maybe it's hiding in `b.fx.misc`, try there. Maybe it's `b.fx.misc.backlight` ?

---------
> None of what I poked around at made a difference. Driver issue possibly?

So none of the lights on the mouse is actually changing when setting them through the daemon using those commands?

In that case, it could be an issue with the daemon. Try a utility called **d-feet**, find the `org.razer` (in the session bus) and try getting/setting the brightness there. It'll likely look a little different to this.

![image](https://cloud.githubusercontent.com/assets/13032135/25155146/771a01b6-248b-11e7-945b-0fe599709eb0.png)

Once I know which functions it's supposed to use, then I can work on amending Polychromatic's logic to show the correct controls.

**Comment by kdb424** [comment]
In [15]: b.fx.misc.backlight.blinking = True

In [16]: b.fx.misc.backlight.brightness = 100

In [17]: b.fx.misc.backlight.static = True

In [18]: b.fx.misc.backlight.brightness = 100

Getting nothing from anything in there unfortunately. As for d-feet

![d-feet](https://cloud.githubusercontent.com/assets/437544/25155503/f0215810-245a-11e7-97a9-13d440e6e85a.png)

**Comment by lah7** [comment]
Since neither the daemon or D-Feet can turn on/off the brightness, I'd suggest [raising an issue on the driver/daemon repository](https://github.com/terrycain/razer-drivers/issues) so they can fix this.

I'll leave this issue open until Polychromatic supports toggling the "backlight" function, which is new.

**Comment by kdb424** [comment]
https://github.com/terrycain/razer-drivers/issues/256 raised issue there. Will report back here when progress is made.

**Comment by terrycain** [comment]
doesnt do brightness, backlight/logo/scroll is either on or off

**Comment by lah7** [comment]
Polychromatic now supports devices that use `backlight`, plus any fixes along the way :+1:

So @kdb424, as soon as you resolve the hardware/driver issue with your mouse (according to your other issue), the brightness toggles *should* work in this app.
