### ISSUE TITLE
Mouse settings affect keyboard as well

### ISSUE THREAD

**Issue by borgdylan** [lah7/polychromatic#79]
I have recently bought a DeathAdder Elite mouse. When I was setting the lighting using polychromatic, the keyboard's brightness and lighting effect settings were being changed to match the mouse's. I expected that the settings controls on the mouse configuration page would only modify the mouse's state and not the keyboard's as well. This issue is only localised to the mouse page. Setting a profile on the keyboard does what is expected i.e. the mouse is left un-modified. In case this is a driver issue, I will file another issue with the driver maintainer.

**Comment by lah7** [comment]
This could have something with the [daemon](https://github.com/terrycain/razer-drivers) -- as it has a feature that sync effects across all devices.

Check `~/.razer-service/razer.conf` for this line:

```
[Startup]
sync_effects_enabled = False
```

Set it to `False` if it's not already, then restart the daemon and see if this fixes the problem.

-------
There was the ability to set daemon settings from within Polychromatic, but apparently this `razer.conf` was being ignored by the daemon... I'll have to check if it's been fixed. :thinking:

**Comment by borgdylan** [comment]
That worked for me, mouse changes no longer affect the keyboard!.

Another question, is support for overflow scrolling in the works? Having colour pickers showing for both wheel and logo makes the UI overlap the brightness box.

**Comment by borgdylan** [comment]
![image](https://cloud.githubusercontent.com/assets/7761010/25290576/ef79b472-26ce-11e7-93e2-a8c8c4a0e935.png)

**Comment by lah7** [comment]
Glad that fixed it :+1: I'll ensure the app warns about that option and turns it off. Apparently that's the only option that works in that config.

I'll close this issue when I've added this `sync_effects_enabled` check.

---------
> Another question, is support for overflow scrolling in the works? Having colour pickers showing for both wheel and logo makes the UI overlap the brightness box.

Overflow causes a problem with a drop-down (if you have many custom colours) so I'm thinking of changing this UI layout at some point. Plus, on the internet somewhere... it's been described as looking a "alien" :thinking:

**Comment by borgdylan** [comment]
About the config file, supported settings seem to be documented in ```man razer.conf```.

**Comment by lah7** [comment]
They're documented, but I've spoken to the driver/daemon developer and he's confirmed that only some work at the moment.
