### ISSUE TITLE
Controller window crash, jquery searching for non-existent files

### ISSUE THREAD

**Issue by mingless** [lah7/polychromatic#82]
### Device: 
Razer Ornata Chroma
### OS: 
Ubuntu 15.10 upgraded to 16.04

### Install: 
Added the ppa's, updated, installed everything.

### Setup: 
Rs per driver wiki, there was no step there to change ownership so I had to manually change group ownership to plugdev for `/usr/share/polychromatic` and appriopriate `/sys/...`, `/dev/...`.

## Issue:
Running `$polychromatic-controller` prompts:
```
CONSOLE ERROR Not allowed to load local resource: file:///usr/share/polychromatic/pages/lib/Play-Regular.ttf
```

but nevertheless loads, then when trying to add a new profile font is undercut and when selecting an application scrolling to the bottom crashes the graphics.

![debug](https://cloud.githubusercontent.com/assets/11635847/25401677/a7029bfc-29f6-11e7-850e-6549421ba5a1.png)

Files mentioned in the prompts don't exist in my install though.

```$ tree /usr/share/polychromatic/pages/
/usr/share/polychromatic/pages/
├── controller.css
├── demo.html
├── error.html
├── global.js
├── lib
│   ├── font-awesome.min.css
│   ├── fontawesome-webfont.woff
│   ├── jquery-2.1.4.min.js
│   └── snap.svg-min.js
├── loading.html
├── menu.html
├── menu.js
├── preferences.html
├── preferences.js
├── profile_editor.html
└── profile_editor.js

1 directory, 15 files
```

**Comment by lah7** [comment]
Both issues have been fixed in `master` ready for the next release. The graphical glitch was unusually fascinating, but they were actually caused by (most likely) LibreOffice's SVGs.

It is a bug in the `WebKit2` library though.

**Comment by mingless** [comment]
Thanks a lot, great work.

And sorry for the pedantry, but line 1402 of the 688495e has a typo, should be `severe` instead of `serve`.
