### ISSUE TITLE
Razer Blade Stealth ( Late 2016 ) - No Devices Found

### ISSUE THREAD

**Issue by chazmead** [lah7/polychromatic#83]
Hey, I'm getting the yellow "No Devices Found" error on your application,  I have run the razer-service in the FG, and there are no errors displayed, the driver apparently supports the 1532:0220  USB device, and lsmod has the razerkbd driver listed.

Please advise what may be the issue, or any kind of fix.

Thanks in advance.

**Comment by lah7** [comment]
Seems highly likely that the daemon isn't recognising your device, Polychromatic feeds in what the daemon says. Which distro are you using?

Is your user definitely in the `plugdev` group? (Make sure to log out then in again)

      sudo gpasswd -a <username> plugdev

If it still doesn't work, please could you post a clean log from the daemon (`~/.razer-service/logs/razer.log`) to [Pastebin](https://pastebin.com/)?

**Comment by chazmead** [comment]
Hey, yes user is definitely in the plugdev group, I am on Debian 9 ( Stretch ) with a custom 4.10.12 linux kernel installed.

Here is a full log output:

> 2017-04-30 14:25:16 | razer                          | INFO     | Initialising Daemon (v1.1.11). Pid: 5895
> 2017-04-30 14:25:16 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2012 --------------------- (1532:010D)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2013 --------------------- (1532:011A)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2016 --------------------- (1532:0214)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassicAlternate --------- (1532:010E)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChromaTournamentEdition - (1532:021A)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderChroma ------------------- (1532:0043)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderElite -------------------- (1532:005C)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerFireFly ---------------------------- (1532:0C00)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerImperiator ------------------------- (1532:002F)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaTE ---------------------- (1532:0046)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
> 2017-04-30 14:25:16 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0208)
> 2017-04-30 14:25:16 | razer                          | INFO     | Adding razer.devices.getDevices method to DBus
> 2017-04-30 14:25:16 | razer                          | INFO     | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
> 2017-04-30 14:25:16 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
> 2017-04-30 14:25:16 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
> 2017-04-30 14:25:16 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
> 2017-04-30 14:25:16 | razer                          | INFO     | Adding razer.daemon.version method to DBus
> 2017-04-30 14:25:16 | razer                          | INFO     | Adding razer.daemon.stop method to DBus
> 2017-04-30 14:25:16 | razer                          | INFO     | Serving DBus
> 2017-04-30 14:25:17 | razer                          | DEBUG    | DBus called get_serial_list
> 2017-04-30 14:25:17 | razer                          | DEBUG    | DBus called get_serial_list

as you see the DBus gets called fine, and the 1532:0220 device is loaded by razer-service, but polychromatic does not recognise the device.

**Comment by lah7** [comment]
Nope, your device isn't loaded by the daemon (`razer-service`) at all for some reason. There should be 2 lines similar to this:

```
2017-04-30 14:28:41 | razer                          | INFO     | Found device.0: 0003:1532:0C00.0001
2017-04-30 14:28:41 | razer.device0                  | INFO     | Initialising device.0 RazerFireFly
```

I see you've got an issue already open regarding the daemon not starting: https://github.com/terrycain/razer-drivers/issues/263 (which is good to know that it starts now!) -- it might be an idea to update that and seek assistance so the driver/daemon guys can take a look, good luck!

Sorry I won't be much of assistance here.
