### ISSUE TITLE
Regressions in latest PPA update

### ISSUE THREAD

**Issue by borgdylan** [lah7/polychromatic#86]
Razer DA Elite: Max DPI is shown as 500 while mouse supports up to 16K
Blackwidow Chroma V2: No effects controls are shown. (Also no polling rate settings are available)

**Comment by borgdylan** [comment]
Also, changing the dpi has left unable to set the dpi to 2500 which was a working value for my mouse.

**Comment by lah7** [comment]
Uh oh, sorry about that. Does this happen in the Tray Applet, Controller or both?

Please run `python3` in the terminal and fetch me the output of the following so I have reference of these devices in future:

```
import razer.client
a = razer.client.DeviceManager()

b = a.devices[0]
b.name
b.capabilities

c = a.devices[1]
c.name
c.capabilities
```

For the mouse, please also run:
```
x.max_dpi
x.poll_rate
```

**Comment by lah7** [comment]
I see in [your other issue](https://github.com/terrycain/razer-drivers/issues/269) the max DPI issue is not Polychromatic's fault, but the daemon has the wrong value... so that's one issue solved.

> The DA Elite has a max DPI of 16000 not 500. The latest polychromatic is depending on the maximum DPI numbers returned by the daemon to limit the DPI values settable by the user.

**Comment by borgdylan** [comment]
I filed a bug against the daemon. It is giving you the bad value for max DPI. In the mean time I set the DPI via DBUS manually. For the keyboard, no polling rate functions are available over DBUS (they are available on the mouse).

So the only actual regression is the effects controls not showing for the keyboard.

**Comment by lah7** [comment]
Please run the `python3` commands above and paste the both of their `capabilities` here. This will be helpful determining what should or shouldn't appear.

**Comment by borgdylan** [comment]
Mouse

```{'lighting_ripple': False, 'lighting_pulsate': False, 'lighting_breath_triple': False, 'lighting_reactive': False, 'lighting_wave': False, 'lighting_breath_dual': False, 'lighting_scroll_reactive': True, 'firmware_version': True, 'lighting_scroll_active': False, 'lighting_breath_single': False, 'poll_rate': True, 'lighting_led_matrix': True, 'lighting_scroll_blinking': False, 'serial': True, 'lighting': True, 'lighting_backlight': False, 'lighting_scroll_pulsate': False, 'lighting_logo_static': True, 'lighting_breath_random': False, 'lighting_logo_active': False, 'lighting_scroll_breath_single': True, 'name': True, 'lighting_scroll_brightness': True, 'lighting_logo_breath_random': True, 'lighting_none': False, 'lighting_logo_spectrum': True, 'lighting_logo_breath_single': True, 'lighting_led_single': False, 'macro_logic': False, 'lighting_scroll_spectrum': True, 'lighting_logo_brightness': True, 'brightness': False, 'dpi': True, 'lighting_scroll': True, 'lighting_scroll_static': True, 'lighting_logo': True, 'lighting_scroll_none': True, 'lighting_logo_blinking': False, 'lighting_backlight_active': False, 'lighting_logo_pulsate': False, 'lighting_static': False, 'lighting_scroll_breath_random': True, 'lighting_logo_reactive': True, 'lighting_logo_none': True, 'lighting_spectrum': False, 'lighting_ripple_random': False, 'lighting_logo_breath_dual': True, 'type': True, 'lighting_scroll_breath_dual': True}```

Keyboard

```{'lighting_ripple': True, 'lighting_pulsate': False, 'lighting_breath_triple': False, 'lighting_reactive': True, 'lighting_wave': True, 'lighting_breath_dual': True, 'lighting_scroll_reactive': False, 'macro_mode_led_effect': True, 'firmware_version': True, 'lighting_scroll_active': False, 'lighting_breath_single': True, 'lighting_led_matrix': True, 'lighting_scroll_blinking': False, 'serial': True, 'lighting': True, 'lighting_backlight': False, 'lighting_scroll_pulsate': False, 'lighting_logo_static': False, 'lighting_breath_random': True, 'lighting_logo_active': False, 'lighting_scroll_breath_single': False, 'name': True, 'lighting_scroll_brightness': False, 'lighting_logo_breath_random': False, 'lighting_none': True, 'lighting_logo_spectrum': False, 'lighting_logo_breath_single': False, 'lighting_led_single': False, 'macro_logic': True, 'lighting_scroll_spectrum': False, 'lighting_logo_brightness': False, 'brightness': True, 'lighting_scroll': False, 'lighting_scroll_static': False, 'lighting_logo': False, 'lighting_scroll_none': False, 'lighting_logo_blinking': False, 'lighting_backlight_active': False, 'macro_mode_led': True, 'lighting_logo_pulsate': False, 'lighting_static': True, 'lighting_scroll_breath_random': False, 'macro_tartarus_mode_modifier': False, 'lighting_logo_reactive': False, 'lighting_logo_none': False, 'lighting_spectrum': True, 'lighting_ripple_random': True, 'lighting_logo_breath_dual': False, 'game_mode_led': True, 'type': True, 'lighting_scroll_breath_dual': False}```

**Comment by lah7** [comment]
Thanks for that, so....

> So the only actual regression is the effects controls not showing for the keyboard.

Is this happening in the Tray Applet, Controller or both?

**Comment by borgdylan** [comment]
I saw it happen in the controller. Haven't tested the tray.

**Comment by borgdylan** [comment]
The tray allowed me to pick an effect no problem. Teh controller shows teh UI once I have done that. SO the bug involves the GUI not appearing if the last set lighting setting was a profile.

**Comment by borgdylan** [comment]
Has the UI been changed to make it more compact? If so how? It may be that I misunderstood the changes and it confused me.

**Comment by lah7** [comment]
Please could you show me a screenshot of what "the issue" looks like?

The UI for the Controller's effects haven't been touched since `v0.3.8`.

**Comment by borgdylan** [comment]
![screenshot from 2017-05-03 22-08-15](https://cloud.githubusercontent.com/assets/7761010/25679269/16e7e132-304d-11e7-8478-50c00cebafe6.png)

Before the drop down clearly indicated that it was for selecting an effect. Putting the profile there mislead me into thinking that the dropdown had gone away.

**Comment by lah7** [comment]
Hmm, no regressions here. This has always been the case, that drop-down shows the currently set "effect" (in this case it's a **custom** one -- "application profile" - static key lighting). I suppose if you didn't see the outline and arrow, it could be misinterpreted.

----------
I also noticed your system is inheriting a WebKit2 alignment bug -- that my work laptop also seems to have... I haven't understood this yet unless it's an Intel graphics thing.

**Yours:**
![image](https://cloud.githubusercontent.com/assets/13032135/25679737/4553d1c2-3046-11e7-80a2-2cb45ac98b01.png)  :point_left: Labels are misaligned

**Should be:**
![image](https://cloud.githubusercontent.com/assets/13032135/25679738/4719ea6e-3046-11e7-92ef-a134e9f0321d.png)

----------

But it's good feedback, the next release will be focusing on profiles and cleaning up the UI a bit. :+1:

**Comment by borgdylan** [comment]
This particular system uses nvidia graphics.
