### ISSUE TITLE
Device not found in Arch Linux

### ISSUE THREAD

**Issue by rudolfschmidt** [lah7/polychromatic#87]
Hi guys,

I have compiled the razer drivers from https://terrycain.github.io/razer-drivers manually (using the source code). After I have compiled polychromatic by source codes too. Starting razer-service without problems I start polychromatic-controller. A window pop out that tells me that my device is not recognized, even I use Razer DeathAddr Chroma that is fully supported by the driver.

Investigating the logs I didnt find anything. The only strange, during boot time I get an error about usbhid that leads that my keyboard is not recognized. If I unplug the mouse, let the system boot and plugin after, everything works fine. i dont know if that could be an issue here too.

**Comment by lah7** [comment]
Hi. As it's a daemon issue you're experiencing, you'd have more luck asking the [driver/daemon repository](https://github.com/terrycain/razer-drivers/issues?utf8=%E2%9C%93&q=is%3Aissue%20arch%20deathadder) for assistance. This isn't a Polychromatic problem as it only asks the daemon for devices, but the daemon says there is none. (From the sound of things, only when the mouse is plugged in during boot?)

@z3ntu is an Arch user, he might be able to help you out. [You could try installing the packages.](https://terrycain.github.io/razer-drivers/#arch)

If you look in `~/razer-service/logs/razer.log` or run `razer-service -F`, you should find lines similar to this:
```
2017-04-30 14:28:41 | razer                          | INFO     | Found device.0: 0003:1532:0C00.0001
2017-04-30 14:28:41 | razer.device0                  | INFO     | Initialising device.0 RazerFireFly
```

**Comment by z3ntu** [comment]
@rudolfschmidt Manually installing the driver is never the best option except there's no distribution package. Following the [Arch instructions](https://terrycain.github.io/razer-drivers/#arch) as @lah7 said is how the driver should be installed.

**Comment by rudolfschmidt** [comment]
I have fixed the problem by installing the driver from the aur packages via pacaur (with yaourt it didnt work because of failed dependencies, even pacaur could resolve the dependencies). Polychromatic works great after that step. Thanks for your work!

**Comment by z3ntu** [comment]
Yes, yaourt is known to not being able to install the package... @lah7 Could you please add a warning to the website under Arch like

```
diff --git a/index.html b/index.html
index 5fc520a..6f0ef06 100644
--- a/index.html
+++ b/index.html
@@ -522,6 +522,12 @@
                     <h4><span class="fa fa-cube"></span>&nbsp;From AUR</h4>
                     <p>Install <a href="https://aur.archlinux.org/packages/openrazer-meta/" target="_blank">openrazer-meta</a> from the AUR.
                     <p>After the drivers are installed, please restart the computer.</p>
+
+                    <div class="danger">
+                      <h5><span class="fa fa-warning"></span>
+                      Due to a bug in yaourt, you get a dependency loop when trying to install it. <code style="color:red">pacaur</code> is confirmed to work.
+                      </h5>
+                    </div>
                   </div>
                 </div>
               </div>
```
