### ISSUE TITLE
Support for Lancehead TE

### ISSUE THREAD

**Issue by moozhub** [lah7/polychromatic#89]
Support for Lancehead TE

**Comment by z3ntu** [comment]
-> https://github.com/terrycain/razer-drivers

**Comment by lah7** [comment]
Hi, this is the wrong place for device support.

[Please create a new issue](https://github.com/terrycain/razer-drivers/issues/new) on the driver/daemon repository and provide these details in the issue description:
> Please post the output of
> `lsusb -d 1532:0036 -v`
> and
> `ls -lah /dev/input/by-id/`
> Read this because we probably need packet captures.
> Screenshots of all available options on Razer Synapse are needed.
> And lastly, the product & model number of the device for documentation reasons please.
