### ISSUE TITLE
Does not start on Ubuntu 16.04

### ISSUE THREAD

**Issue by claell** [lah7/polychromatic#9]
I installed the application, but it does not start for me. Is there a command line start option to see what is wrong?

**Comment by lah7** [comment]
Hi there. Did you install the one in `master` or the [v.0.1.0](https://github.com/lah7/polychromatic/releases/tag/v0.1.0) deb package?

For the `master` version, you can run it from the terminal:

    polychromatic-controller

`master` has recently been ported to WebKit2, which requires **gir1.2-webkit2-4.0** and not **gir1.2-webkit-3.0** any more, which could be possibly why it is not starting. [The README has been fixed](https://github.com/lah7/polychromatic/pull/8).

**Comment by claell** [comment]
I installed the deb package.

**Comment by lah7** [comment]
What is the output of: `/usr/share/polychromatic/controller.py` ?

**Comment by claell** [comment]
Loading preferences from "/home/clel/.config/polychromatic/preferences.json'...
Successfully loaded preferences.
Failed to connect to the dbus service. Is the razer_bcd service running?

**Comment by lah7** [comment]
> Failed to connect to the dbus service. Is the razer_bcd service running?

Polychromatic works, but the [razer-chroma-drivers](https://github.com/pez2001/razer_chroma_drivers) service isn't running or installed properly -- it could be similar this one: https://github.com/pez2001/razer_chroma_drivers/issues/121.

If that solution doesn't work, [search the closed issues on the driver's page](https://github.com/pez2001/razer_chroma_drivers/issues?utf8=%E2%9C%93&q=is%3Aissue+) to investigate why the daemon/service isn't loading.

**Comment by claell** [comment]
I only have a Razer Abyssus mouse connected. Do I need to connect a keyboard in order to use the configuration tool?

**Comment by lah7** [comment]
I don't think your Razer Abyssus is supported by the driver?
https://github.com/pez2001/razer_chroma_drivers/issues/114

The utility can only work with one Razer device at a time. It was originally designed for the Razer BlackWidow range of keyboards but this will change when multi-device support is added.

**Comment by claell** [comment]
I think it has been added: https://github.com/pez2001/razer_chroma_drivers/pull/118

**Comment by lah7** [comment]
So it is! Looks like the website/README wants updating.

I'm sorry, but I'm not sure how to resolve the problem since this is related to the driver. :confused:

Is the service definitely running? What do you see here:

    sudo service razer_bcd status

It should output a line similar to this:

>    **Active: active (running)** since Tue 2016-05-24 13:14:33 BST; 4h 57min ago

**Comment by claell** [comment]
I just reinstalled the driver, but still need to reboot to check whether it helped. If not I guess I will create an issue on the driver page.

**Comment by claell** [comment]
Still not working, I opened an issue on the driver page now.

For the future it might be good to display an error message so the user knows what is wrong.

**Comment by lah7** [comment]
Thanks for the suggestion. This utility is on its way for a major revamp. 😊

**Comment by claell** [comment]
Sounds good :+1:

**Comment by goliney** [comment]
@lah7 you should consider adding commands like `polychromatic-controller` to the README, because noobs like me do not know what to do next after an installation is complete :)
