### ISSUE TITLE
ubuntu 16.04.2 freezes on restart/shutdown after Polychromatic install

### ISSUE THREAD

**Issue by Dans-git** [lah7/polychromatic#94]
I'm not sure what info to supply as I haven't been able to find the specific error, but here goes...

Following the instructions [here](https://github.com/lah7/polychromatic), I got the Razer Drivers and Polychromatic to succesfully install.
Directly after installing Polychromatic, I proceeded to restart my computer, but the system now freezes.. forcing me to hard restart the system.

Has anyone else had this issue??

I have also reported the issue on the Ubuntu Forums and am still awaiting replay there..

`uname -r` reports 4.8.0-53-generic

`sudo systemctl reboot` `sudo swapoff -a` `sudo swapoff -a && sudo systemctl reboot` `sudo swapoff -a && sudo systemctl poweroff`

```sudo gedit /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"    
to   
GRUB_CMDLINE_LINUX_DEFAULT="acpi=force"   
Save and Exit gedit
Run update-grub
```

```sudo gedit /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"    
to   
GRUB_CMDLINE_LINUX_DEFAULT="acpi=noirq"   
Save and Exit gedit
Run update-grub
```

Set USB Legacy Mode to "DISABLED" in my bios

None of these approaches have been succesfull nor brought me any closer to identifying exactly what the problem is, though these freezes only started happening AFTER the installation of Polychromatic.

I'm hoping someone here can help..
...and of course I can try to supply more info upon request.

Pressing ESC at the splash screen gives me the following output:
![img_20170601_075954](https://cloud.githubusercontent.com/assets/29098180/26666531/b74d6a70-46a0-11e7-9d8c-2a9234762391.jpg)

At "Reached target Shutdown" is where the system freezes.

**Comment by lah7** [comment]
From what I gather, you installed the Razer drivers [(which are external to this application)](https://github.com/terrycain/razer-drivers) --> Polychromatic --> then **restarted**?

It seems very unlikely Polychromatic would cause a freeze at boot, unless for some reason one of its dependencies are an issue. It's most likely the drivers that caused the freeze.

Which Razer device do you have? Does it boot when it's unplugged?

-------
Try uninstalling them from recovery mode. Hold SHIFT while booting to show GRUB, then enter the one marked with `(Recovery)` and from there, you can drop to a root shell. Try uninstalling both the Razer driver and this application:

    sudo apt remove polychromatic python3-razer razer-kernel-modules-dkms razer-daemon razer-doc
    sudo apt autoremove
    sudo reboot

If your system boots again, try gathering some logs of the error and raise an issue on the [driver repository](https://github.com/terrycain/razer-drivers). Polychromatic is just a front-end, it's extremely unlikely to be responsive for a boot issue.

**Comment by Dans-git** [comment]
Indeed. I installed the Razer Drivers and restarted. After that restart,  I installed Polychromatic and restarted.. this time my system froze. 

My thoughts are also that it's due to a dependency though I don't know where to begin searching for the logs pertaining to restarts and shutdowns.. I'm still kind of new to the Linux system :) 

I have the Razer Deathstalker keyboard and the Razer Diamondback mouse. Both are Chroma versions and supported by the Razer drivers and Polychromatic. 
Does what boot when it's unplugged? 

I will try your advice tomorrow morning and get back with the results. Also, I will try to find out where the logs are stored and post that info as well.

**Comment by ldartez** [comment]
what is the output of `dmesg`?
as mentioned by Iah7, try backtracking the entire installation. It could also be that your system doesn't like the changes you made to grub, so I would probably start there.

I believe Iah7 was asking if your system would boot when your Razer devices (mouse and keyboard) are *not* plugged in.

**Comment by Dans-git** [comment]
Hi Idartez,

Here's the output of dmesg.. 
[DMESG.TXT](https://github.com/lah7/polychromatic/files/1043760/DMESG.TXT)

I'll try lah7's advice now.

**Comment by Dans-git** [comment]
Results of booting with devices unplugged:

Only keyboard unplugged - system boots though I recieve the typical "no keyboard, press f1 to continue" message, but the boot continues normally and I reach the Ubuntu login screen where I have to type in my password.

Only mouse unplugged - system boots normally and I reach the Ubuntu login screen

Both devices unplugged - system boots normally though I recieve the typical "no keyboard, press F1 to continue message, but the boot continues normally and I reach the Ubuntu login screen

**Comment by Dans-git** [comment]
Iah7,
I get a dpkg error when running your command in recovery mode..
`dpkg: error: unable to access dpkg status area: Read-only file system
touch: cannot touch '/var/lib/update-notifier/dpkg-run-stamp': Read-only file system
W: Not using locking for read only lock file /var/lib/dpkg/lock
W: chown to _apt :root of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (30: Read-only file system)
W: chmod 0700 of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (30: Read-only file system)
W: Not using locking for read only lock file /var/cache/apt/archives/lock
E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (30: Read-only file system)
E: Failed to write temporary StateFile /var/lib/apt/extended_states
W: Could not open file '/var/log/apt/term.log' - OpenLog (30: Read-only file system)
E: Sub-proces /usr/bin/dpkg returned an error code (2)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - pkgDPkgPM: :Go (30: Read-only file system)`

**Comment by ldartez** [comment]
@Dans-git, 

I was referring to the GRUB changes you mentioned trying out in your original post. I didn't see anything immediately obviously wrong in your dmesg output. As far as the read-only file system problem you're having: It looks like the recovery shell booted directly into read-only mode (mine does that). In order to make changes on disk you first need to find out what what your root disk identifier is. the output of `mount` should reveal which drive is mounted onto `/`. then run `mount -t ext4 -o remount,rw /dev/sda1 /', where `ext4` is changed to your FS format and `/dev/sda1` is changed to your root disk identifier.

**Comment by Dans-git** [comment]
That would have been handy to know about 5 minutes ago, before I ran Iah7's command on regular terminal XD

**Comment by lah7** [comment]
Oops, I forgot that recovery mode boots into a read only system. So from what I can see:

* When one or both devices are unplugged, they reach the login screen just fine.
* They're both unInstalled now so we can try again.
* You're booting in BIOS Legacy mode, so UEFI / secure boot won't be a problem.

**Protip:** For a one off verbose output, when on the GRUB screen, press **e** to edit the boot commend then remove the `quiet splash` part, then (I think) F10 to boot.

Try installing the drivers again, and reboot. Then try installing Polychromatic again, then reboot for safe measure.

Then we'll see which one is actually the culprit and work from there.

**Comment by Dans-git** [comment]
@lah7
I installed the drivers again 
[razerdrivers.txt](https://github.com/lah7/polychromatic/files/1045016/razerdrivers.txt)
and afterwards rebooted with no issues..

After that I installed Polychromatic again
[polychromatic.txt](https://github.com/lah7/polychromatic/files/1045022/polychromatic.txt)
and afterwards rebooted with no issues.. Wierd!

I'll install my video drivers now (AMDGPU-PRO) and see if it's the combination of AMDGPU-PRO and Razer/Polychromatic that is causing conflicts somewhere.

**Comment by lah7** [comment]
Glad to hear. :+1: If the AMDGPU-PRO drivers cause a faulty boot and you can prove it's the Razer stuff at fault, please [raise an issue on the drivers repository](https://github.com/terrycain/razer-drivers).
