### ISSUE TITLE
Driver Issue (?)

### ISSUE THREAD

**Issue by adi105** [lah7/polychromatic#99]
When I run Polychromatic, a few things happen. Firstly, in the console it states "Gtk-Message: Failed to load module "canberra-gtk-module"". The program still runs, however it states that the razer daemon is not running, and attempting to force reset yields this error:
Traceback (most recent call last):
  File "/usr/bin/razer-daemon", line 9, in <module>
    from razer_daemon.daemon import daemonize
ModuleNotFoundError: No module named 'razer_daemon'
I believe I have installed all of the razer drivers for linux correctly, and yet this error appears. What should I do?

**Comment by lah7** [comment]
Which distro? The modules for the daemon cannot be found, either because they're missing (not installed) or your environment variable for Python libraries (`PYTHONPATH`) is looking in the wrong place.

In Ubuntu, they would be installed in `/usr/lib/python3/dist-packages/razer_daemon`.

You should check they do exist and that the path is correct:

    PYTHONPATH="${PYTHONPATH}:/path/to/lib/folder"
    export PYTHONPATH
    razer-drivers -F

**Comment by adi105** [comment]
I'm running Kali Linux, so it's off of Debian, but I'm not sure which version. I think there was an issue where Polychromatic was running off of the incorrect version of python, but I think now I have everything set up to run the right version. This time, when I run razer-daemon, it works, and razer-daemon -F says:
2017-06-21 11:40:17 | razer                          | INFO     | Initialising Daemon (v1.1.13). Pid: 5353
2017-06-21 11:40:17 | razer                          | CRITICAL | User is not a member of the plugdev group

When I run polychromatic, it says the same things about not being able to run the daemon. It's strange that after I run razer-daemon, and it is for sure running, Polychromatic still cannot detect it. What should I do next?

**Comment by adi105** [comment]
I fixed it by adding root user to plugdev, which I didn't think was necessary. Works like a charm now :)
